// COPYRIGHT 上海文颢信息技术有限公司 2018
//===================================================================
//
// DebugDBServicesCmd.h
// The state chart based command: DebugDBServicesCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   STATECOMMAND
//End CAA2 Wizard Generation Report
//
//  Apr 2018  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#ifndef DebugDBServicesCmd_H
#define DebugDBServicesCmd_H

#include "CATStateCommand.h"
#include "CATBoolean.h"

//----------------------------------------------------------------------

/**
 * Describe your command here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog engine framework.
 * (consult base class description).
 */
class DebugDBServicesCmd: public CATStateCommand
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( DebugDBServicesCmd, CATStateCommand )

  public:

	  DebugDBServicesCmd();
	  virtual ~DebugDBServicesCmd();

		/**
		 * Defines the command automata.
		 * <br>
		 * <i>(states, transitions and agents)</i>
		 */
	  virtual void     BuildGraph();


  private:

};

//----------------------------------------------------------------------

#endif
