// COPYRIGHT Dassault Systemes 2019
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework SYAddinFrm
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Mar 2019  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("System",Protected);
AddPrereqComponent("ApplicationFrame",Protected);
// END WIZARD EDITION ZONE
