// COPYRIGHT Dassault Systemes 2009
//===================================================================
//
// JDAEPTBaseSelectShow.cpp
// Provide implementation to interface
//    CATISelectShow
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Apr 2009  Creation: Code generated by the CAA wizard  LuJun
//===================================================================
#include "JDAEPTBaseSelectShow.h"

#include "iostream.h"

 
CATImplementClass(JDAEPTBaseSelectShow,
                  DataExtension,
                  CATExtISelectShow,
                  JDAPTBase );
 

//-----------------------------------------------------------------------------
// JDAEPTBaseSelectShow : constructor
//-----------------------------------------------------------------------------
JDAEPTBaseSelectShow::JDAEPTBaseSelectShow():
    CATExtISelectShow()
{
}

//-----------------------------------------------------------------------------
// JDAEPTBaseSelectShow : destructor
//-----------------------------------------------------------------------------
JDAEPTBaseSelectShow::~JDAEPTBaseSelectShow()
{
}
 
// Link the implementation to its interface
// ---------------------------------------



//TIE or TIEchain definitions
#include "TIE_CATISelectShow.h"
TIE_CATISelectShow( JDAEPTBaseSelectShow);


//Methods implementation

//-----------------------------------------------------------------------------
// Implements CATISelectShow::GetSelectShowInterface
//-----------------------------------------------------------------------------
//const IID & JDAEPTBaseSelectShow::GetSelectShowInterface ()
//{
//
//}

//-----------------------------------------------------------------------------
// Implements CATISelectShow::GetElement
//-----------------------------------------------------------------------------
CATBaseUnknown * JDAEPTBaseSelectShow::GetElement (CATPathElement * iPathElt)
{
	//cout <<"==> Now we are in JDAEPTBaseSelectShow::GetElement  !" << endl;
	return this;
}

//-----------------------------------------------------------------------------
// Implements CATISelectShow::GetElementForHideShow
//-----------------------------------------------------------------------------
HRESULT JDAEPTBaseSelectShow::GetElementForHideShow (CATPathElement * iPathElt , CATBaseUnknown *&  oSelectedObject , int&  oPostProcess)
{
	//cout <<"==> Now we are in JDAEPTBaseSelectShow::GetElementForHideShow  !" << endl;
	oSelectedObject = this;
	oPostProcess = 0;

	return S_OK;
}
//
////-----------------------------------------------------------------------------
//// Implements CATISelectShow::SelectShowPostProcess
////-----------------------------------------------------------------------------
//HRESULT JDAEPTBaseSelectShow::SelectShowPostProcess (CATPathElement * iPathElt , CATShowAttribut  iShowAttr)
//{
//
//   return S_OK;
//}

