// COPYRIGHT 上海文颢信息技术有限公司 2017
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework WinhoDBPubLib
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Jun 2017  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("System",Protected);
// END WIZARD EDITION ZONE
AddPrereqComponent("WinhoCAAPubLib",Public);
//AddPrereqComponent("WinhoJSONPubLib",Public);

