// COPYRIGHT 上海文颢信息技术有限公司 2018
//===================================================================
//
// WINDebugAddin.h
// Provide implementation to interface
//    CATIAfrGeneralWksAddin

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	DebugAddin
//EXTENSIONTYPE:	DataExtension

//    TIE: CATIAfrGeneralWksAddin

//End CAA2 Wizard Generation Report
//
//  Apr 2018  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#ifndef WINDebugAddin_H
#define WINDebugAddin_H

#include "CATBaseUnknown.h"
#include "CATCommandHeader.h"
#include "CATCreateWorkshop.h"
#include "CATCmdContainer.h"

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href CATIAfrGeneralWksAddin
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class WINDebugAddin: public CATBaseUnknown

{
  CATDeclareClass;

  public:

	  // Standard constructors and destructors for an implementation class
	  // -----------------------------------------------------------------
	  WINDebugAddin ();
	  virtual ~WINDebugAddin ();

	  void CreateCommands();
	  CATCmdContainer * CreateToolbars();


  private:
	  // The copy constructor and the equal operator must not be implemented
	  // -------------------------------------------------------------------
	  WINDebugAddin (WINDebugAddin &);
	  WINDebugAddin& operator=(WINDebugAddin&);

};

//-----------------------------------------------------------------------

#endif
