// COPYRIGHT Dassault Systemes 2009
//===================================================================
//
// JDAEPTMemoAlias.cpp
// Provide implementation to interface
//    CATIAlias
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Apr 2009  Creation: Code generated by the CAA wizard  LuJun
//===================================================================
#include "JDAEPTMemoAlias.h"
#include "CATISpecObject.h"
#include "iostream.h"


 
CATImplementClass(JDAEPTMemoAlias,
                  DataExtension,
                  CATBaseUnknown,
                  JDAPTMemo );
 

//-----------------------------------------------------------------------------
// JDAEPTMemoAlias : constructor
//-----------------------------------------------------------------------------
JDAEPTMemoAlias::JDAEPTMemoAlias():
    CATBaseUnknown()
{
	//cout <<"==> In JDAEPTMemoAlias ......" << endl;
}

//-----------------------------------------------------------------------------
// JDAEPTMemoAlias : destructor
//-----------------------------------------------------------------------------
JDAEPTMemoAlias::~JDAEPTMemoAlias()
{
	//cout <<"==> In JDAEPTMemoAlias ......end !" << endl;
}
 
// Link the implementation to its interface
// ---------------------------------------



//TIE or TIEchain definitions
#include "TIE_CATIAlias.h"
TIE_CATIAlias( JDAEPTMemoAlias);


//Methods implementation

//-----------------------------------------------------------------------------
// Implements CATIAlias::SetAlias
//-----------------------------------------------------------------------------
void JDAEPTMemoAlias::SetAlias (const CATUnicodeString&  iName )
{
	//cout <<"==> Now we are in JDAEPTMemoAlias::SetAlias  !" << endl;

	CATISpecObject_var spSpec = this;
	spSpec->SetName(iName);

	//cout <<"==> Now end JDAEPTMemoAlias::SetAlias  !" << endl;

    return;
}

//-----------------------------------------------------------------------------
// Implements CATIAlias::GetAlias
//-----------------------------------------------------------------------------
CATUnicodeString JDAEPTMemoAlias::GetAlias ()
{
	//cout <<"==> Now we are in JDAEPTMemoAlias::GetAlias  !" << endl;

	CATISpecObject_var spSpec = this;
    return (spSpec->GetName());

	//cout <<"==> Now end JDAEPTMemoAlias::GetAlias  !" << endl;
}

