// COPYRIGHT Dassault Systemes 2009
//===================================================================
//
// DJAEPTMemoNavigate.h
// Provide implementation to interface
//    CATINavigateObject

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	JDAPTMemo
//EXTENSIONTYPE:	DataExtension

//    TIE: CATINavigateObject

//End CAA2 Wizard Generation Report
//
//  May 2009  Creation: Code generated by the CAA wizard  LuJun
//===================================================================
#ifndef DJAEPTMemoNavigate_H
#define DJAEPTMemoNavigate_H

#include "CATBaseUnknown.h"
class CATListValCATUnicodeString;
class CATListValCATBaseUnknown_var;

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href CATINavigateObject
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class DJAEPTMemoNavigate: public CATBaseUnknown

{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     DJAEPTMemoNavigate ();
     virtual ~DJAEPTMemoNavigate ();

    /**
     * Implements a function from an interface.
     * @href CATINavigateObject#GetIdentificators
     */
     CATListValCATUnicodeString* GetIdentificators () ;

    /**
     * Implements a function from an interface.
     * @href CATINavigateObject#GetChildren
     */
     CATListValCATBaseUnknown_var* GetChildren () ;


  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  DJAEPTMemoNavigate (DJAEPTMemoNavigate &);
  DJAEPTMemoNavigate& operator=(DJAEPTMemoNavigate&);

};

//-----------------------------------------------------------------------

#endif
