// COPYRIGHT Dassault Systemes 2009
//===================================================================
//
// JDAEPTMemoVisProperties.h
// Provide implementation to interface
//    CATIVisProperties

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	JDAPTMemo
//EXTENSIONTYPE:	DataExtension

//    TIE: CATIVisProperties

//End CAA2 Wizard Generation Report
//
//  Apr 2009  Creation: Code generated by the CAA wizard  LuJun
//===================================================================
#ifndef JDAEPTMemoVisProperties_H
#define JDAEPTMemoVisProperties_H

#include "CATExtIVisProperties.h"
class CATPathElement;


//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href CATIVisProperties
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class JDAEPTMemoVisProperties: public CATExtIVisProperties

{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     JDAEPTMemoVisProperties ();
     virtual ~JDAEPTMemoVisProperties ();

	 HRESULT IsGeomTypeDefined(CATVisGeomType& iGeomType);
     HRESULT GetSubTypeFromPath(
                                 CATPathElement     & iPathElement,
                                 CATVisPropertyType   iPropertyType,
                                 CATVisGeomType     & oGeomType,
                                 unsigned int       & oPropertyNumber );



  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  JDAEPTMemoVisProperties (JDAEPTMemoVisProperties &);
  JDAEPTMemoVisProperties& operator=(JDAEPTMemoVisProperties&);

};

//-----------------------------------------------------------------------

#endif
