// COPYRIGHT Dassault Systemes 2009
//===================================================================
//
// JDAEPTMemo3DVisu.h
// Provide implementation to interface
//    CATI3DGeoVisu

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	JDAPTMemo
//EXTENSIONTYPE:	DataExtension

//    TIE: CATI3DGeoVisu

//End CAA2 Wizard Generation Report
//
//  Apr 2009  Creation: Code generated by the CAA wizard  LuJun
//===================================================================
#ifndef JDAEPTMemo3DVisu_H
#define JDAEPTMemo3DVisu_H

#include "CATExtIVisu.h"
#include "CATRep.h"

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href CATI3DGeoVisu
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class JDAEPTMemo3DVisu: public CATExtIVisu

{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     JDAEPTMemo3DVisu ();
     virtual ~JDAEPTMemo3DVisu ();

	 CATRep * BuildRep ();

  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  JDAEPTMemo3DVisu (JDAEPTMemo3DVisu &);
  JDAEPTMemo3DVisu& operator=(JDAEPTMemo3DVisu&);

};

//-----------------------------------------------------------------------

#endif
