// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework WinhoCAAPubLib
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Apr 2015  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("System",Protected);
// END WIZARD EDITION ZONE
AddPrereqComponent("Dialog",Public);
AddPrereqComponent("ApplicationFrame",Public);
AddPrereqComponent("ObjectSpecsModeler",Public);
AddPrereqComponent("MecModInterfaces",Public);
AddPrereqComponent("ProductStructure",Public);
AddPrereqComponent("NewTopologicalObjects",Public);
AddPrereqComponent("Mathematics",Public);
AddPrereqComponent("DMAPSInterfaces",Public);
AddPrereqComponent("ObjectModelerBase",Public);
AddPrereqComponent("KnowledgeInterfaces",Public);
AddPrereqComponent("VisualizationBase",Public);
AddPrereqComponent("Visualization",Public);
AddPrereqComponent("ProductStructureInterfaces",Public);
AddPrereqComponent("InfInterfaces",Public);
AddPrereqComponent("InteractiveInterfaces",Public);
AddPrereqComponent("CATIAApplicationFrame",Public);
AddPrereqComponent("GeometricObjects",Public);  
AddPrereqComponent("Tessellation",Public);  
AddPrereqComponent("GSMInterfaces",Public);
AddPrereqComponent("PartInterfaces",Public);
AddPrereqComponent("MechanicalModelerUI",Public);
AddPrereqComponent("MechanicalModeler",Public);
//以下用于ENOVIA
AddPrereqComponent("ENOVaultClientCPP",Public);
AddPrereqComponent("TopologicalOperators",Public);
AddPrereqComponent("BasicTopologicalOpe",Public);
 
 
 