// COPYRIGHT Dassault Systemes 2009
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework JDPrdAppFrmUI
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Apr 2009  Creation: Code generated by the CAA wizard  LuJun
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("System",Protected);
AddPrereqComponent("DialogEngine",Protected);
AddPrereqComponent("Mathematics",Protected);
AddPrereqComponent("Dialog",Protected);
AddPrereqComponent("ApplicationFrame",Protected);
AddPrereqComponent("ProductStructureUI",Protected);
AddPrereqComponent("JDAPointInterfaces",Protected);
AddPrereqComponent("ObjectModelerBase",Protected);
AddPrereqComponent("ObjectSpecsModeler",Protected);
AddPrereqComponent("ProductStructure",Protected);
AddPrereqComponent("ObjectModelerNavigator", Protected);
// END WIZARD EDITION ZONE
AddPrereqComponent("VisualizationBase",Protected);
