// COPYRIGHT Dassault Systemes 2012
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework SJDRelinkDrawingPartFrm
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Jul 2012  Creation: Code generated by the CAA wizard  THINKPAD
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("System",Public);
// END WIZARD EDITION ZONE
AddPrereqComponent("ObjectModelerBase",Public);
AddPrereqComponent("DraftingInterfaces",Public);
AddPrereqComponent("ObjectSpecsModeler",Public);
AddPrereqComponent("CATxPDMInterfaces",Public);
AddPrereqComponent("Mathematics",Public);
AddPrereqComponent("ProductStructure",Public);
