// COPYRIGHT Dassault Systemes 2010
//===================================================================
//
// JDAEPTMemoParmEvents.h
// Provide implementation to interface
//    JDAIPTMemoParmEvents

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	JDAPTMemo
//EXTENSIONTYPE:	DataExtension

//    TIE: JDAIPTMemoParmEvents

//End CAA2 Wizard Generation Report
//
//  Oct 2010  Creation: Code generated by the CAA wizard  LuJun
//===================================================================
#ifndef JDAEPTMemoParmEvents_H
#define JDAEPTMemoParmEvents_H

#include "CATBaseUnknown.h"
#include "CATEventSubscriberTypedefs.h"
#include "CATICkeParm.h"

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href JDAIPTMemoParmEvents
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class JDAEPTMemoParmEvents: public CATBaseUnknown

{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     JDAEPTMemoParmEvents ();
     virtual ~JDAEPTMemoParmEvents ();

    /**
     * Implements a function from an interface.
     * @href JDAIPTMemoParmEvents#OnChangeValueEvent
     */

	 void AddSubscribe (CATICkeParm_var &iParameterToObserve);

	 void RemoveSubscribe ( CATICkeParm_var &iParameterToObserve);

     void OnChangeValueEvent (CATCallbackEvent  iEvent  , void*  iFrom  , CATNotification*  iNotification  , CATSubscriberData  iInfo  , CATCallback  iCallback ) ;


  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  JDAEPTMemoParmEvents (JDAEPTMemoParmEvents &);
  JDAEPTMemoParmEvents& operator=(JDAEPTMemoParmEvents&);

};

//-----------------------------------------------------------------------

#endif
