// COPYRIGHT Dassault Systemes 2009
//===================================================================
//
// JDAEPTBaseEvents.h
// Provide implementation to interface
//    CATIModelEvents

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	JDAPTBase
//EXTENSIONTYPE:	DataExtension

//    TIE: CATIModelEvents

//End CAA2 Wizard Generation Report
//
//  Apr 2009  Creation: Code generated by the CAA wizard  LuJun
//===================================================================
#ifndef JDAEPTBaseEvents_H
#define JDAEPTBaseEvents_H

#include "CATExtIModelEvents.h"

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href CATIModelEvents
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class JDAEPTBaseEvents: public CATExtIModelEvents

{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     JDAEPTBaseEvents ();
     virtual ~JDAEPTBaseEvents ();

  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  JDAEPTBaseEvents (JDAEPTBaseEvents &);
  JDAEPTBaseEvents& operator=(JDAEPTBaseEvents&);

};

//-----------------------------------------------------------------------

#endif
