// COPYRIGHT Dassault Systemes 2009
//===================================================================
//
// JDAEPTBaseDescendants.h
// Provide implementation to interface
//    CATIDescendants

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	JDAPTBase
//EXTENSIONTYPE:	CodeExtension

//    TIE: CATIDescendants

//End CAA2 Wizard Generation Report
//
//  Apr 2009  Creation: Code generated by the CAA wizard  LuJun
//===================================================================
#ifndef JDAEPTBaseDescendants_H
#define JDAEPTBaseDescendants_H

#include "CATBaseUnknown.h"
#include "CATISpecAttrKey.h"
class CATISpecObject_var;
class CATListValCATISpecObject_var;


//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href CATIDescendants
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class JDAEPTBaseDescendants: public CATBaseUnknown

{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     JDAEPTBaseDescendants ();
     virtual ~JDAEPTBaseDescendants ();

    /**
     * Implements a function from an interface.
     * @href CATIDescendants#Append
     */
     void Append (const CATISpecObject_var &  iFeature  ) ;

    /**
     * Implements a function from an interface.
     * @href CATIDescendants#Prepend
     */
     void Prepend (const CATISpecObject_var &  iFeature ) ;

    /**
     * Implements a function from an interface.
     * @href CATIDescendants#AddChild
     */
     void AddChild (const CATISpecObject_var &  iFeature  , int  iPosition ) ;

    /**
     * Implements a function from an interface.
     * @href CATIDescendants#RemoveChild
     */
     void RemoveChild (const CATISpecObject_var &  iFeature  ) ;

    /**
     * Implements a function from an interface.
     * @href CATIDescendants#GetPosition
     */
     int GetPosition (const CATISpecObject_var &  iFeature  ) ;

    /**
     * Implements a function from an interface.
     * @href CATIDescendants#ChangePosition
     */
     void ChangePosition (const CATISpecObject_var &  iFeature  , int  iNewPosition  ) ;

    /**
     * Implements a function from an interface.
     * @href CATIDescendants#GetChildAtPosition
     */
     CATISpecObject_var GetChildAtPosition (int  iPosition  ) ;

    /**
     * Implements a function from an interface.
     * @href CATIDescendants#GetNumberOfChildren
     */
     int GetNumberOfChildren () ;

    /**
     * Implements a function from an interface.
     * @href CATIDescendants#GetDirectChildren
     */
     void GetDirectChildren (CATClassId  iIntfName  , CATListValCATISpecObject_var & oLst ) ;

    /**
     * Implements a function from an interface.
     * @href CATIDescendants#GetAllChildren
     */
     void GetAllChildren (CATClassId  iIntfName  , CATListValCATISpecObject_var & oLst ) ;


  private:

	  CATISpecAttrKey *GetComponentKey ();
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  JDAEPTBaseDescendants (JDAEPTBaseDescendants &);
  JDAEPTBaseDescendants& operator=(JDAEPTBaseDescendants&);
  //CATISpecAttrKey *_piListComponentKey;
};

//-----------------------------------------------------------------------

#endif
