// COPYRIGHT Dassault Systemes 2009
//===================================================================
//
// JDAEPTMemoFactory.h
// Provide implementation to interface
//    JDAIPTMemoFactory

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	JDAPTContainer
//EXTENSIONTYPE:	DataExtension

//    TIE: JDAIPTMemoFactory

//End CAA2 Wizard Generation Report
//
//  Apr 2009  Creation: Code generated by the CAA wizard  LuJun
//===================================================================
#ifndef JDAEPTMemoFactory_H
#define JDAEPTMemoFactory_H

#include "CATBaseUnknown.h"
#include "JDAIPTMemo.h"

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href JDAIPTMemoFactory
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class JDAEPTMemoFactory: public CATBaseUnknown

{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     JDAEPTMemoFactory ();
     virtual ~JDAEPTMemoFactory ();

    /**
     * Implements a function from an interface.
     * @href JDAIPTMemoFactory#CreateJDAPoint
     */
     HRESULT CreateJDAPoint (double  iX  , double  iY  , double  iZ  , JDAIPTMemo ** oPT ) ;


  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  JDAEPTMemoFactory (JDAEPTMemoFactory &);
  JDAEPTMemoFactory& operator=(JDAEPTMemoFactory&);

};

//-----------------------------------------------------------------------

#endif
