// COPYRIGHT Dassault Systemes 2009
//===================================================================
//
// JDAEPTContainer.h
// Provide implementation to interface
//    JDAIPTContainer

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	JDAPTContainer
//EXTENSIONTYPE:	DataExtension

//    TIE: JDAIPTContainer

//End CAA2 Wizard Generation Report
//
//  Apr 2009  Creation: Code generated by the CAA wizard  LuJun
//===================================================================
#ifndef JDAEPTContainer_H
#define JDAEPTContainer_H

#include "CATBaseUnknown.h"
class JDAIPTRoot;


//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href JDAIPTContainer
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class JDAEPTContainer: public CATBaseUnknown

{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     JDAEPTContainer ();
     virtual ~JDAEPTContainer ();

    /**
     * Implements a function from an interface.
     * @href JDAIPTContainer#GetRoot
     */
     HRESULT GetRoot (JDAIPTRoot ** opiRoot ) ;


  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  JDAEPTContainer (JDAEPTContainer &);
  JDAEPTContainer& operator=(JDAEPTContainer&);

  JDAIPTRoot *_piRoot;
};

//-----------------------------------------------------------------------

#endif
