// COPYRIGHT Dassault Systemes 2009
//===================================================================
//
// JDAPTParmProvider.h
// Provide implementation to interface
//    CATIParmProvider

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//IMPLEMENTATION
//    TIE: CATIParmProvider

//End CAA2 Wizard Generation Report
//
//  Apr 2009  Creation: Code generated by the CAA wizard  LuJun
//===================================================================
#ifndef JDAPTParmProvider_H
#define JDAPTParmProvider_H

#include "CATBaseUnknown.h"
class CATListValCATBaseUnknown_var;

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href CATIParmProvider
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class JDAPTParmProvider: public CATBaseUnknown

{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     JDAPTParmProvider ();
     virtual ~JDAPTParmProvider ();

     /**
     * Implements a function from an interface.
     * @href CATIParmProvider#GetDirectChildren
     */
     HRESULT GetDirectChildren (CATClassId  intfName  , CATListValCATBaseUnknown_var*  oList  , CATBaseUnknown*  iObj ) ;


  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  JDAPTParmProvider (JDAPTParmProvider &);
  JDAPTParmProvider& operator=(JDAPTParmProvider&);

};

//-----------------------------------------------------------------------

#endif
