// COPYRIGHT Dassault Systemes 2009
//===================================================================
//
// JDAPT3DVisuProvider.h
// Provide implementation to interface
//    CATI3DVisuProvider

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//IMPLEMENTATION
//    TIE: CATI3DVisuProvider

//End CAA2 Wizard Generation Report
//
//  Apr 2009  Creation: Code generated by the CAA wizard  LuJun
//===================================================================
#ifndef JDAPT3DVisuProvider_H
#define JDAPT3DVisuProvider_H

#include "CATBaseUnknown.h"
#include "CATListOfCATBaseUnknown.h"

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href CATI3DVisuProvider
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class JDAPT3DVisuProvider: public CATBaseUnknown

{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     JDAPT3DVisuProvider ();
     virtual ~JDAPT3DVisuProvider ();

     /**
     * Implements a function from an interface.
     * @href CATI3DVisuProvider#GetChildren
     */
     HRESULT GetChildren (CATBaseUnknown *  iObj  , CATLISTP(CATBaseUnknown) **  oListChildren ) ;


  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  JDAPT3DVisuProvider (JDAPT3DVisuProvider &);
  JDAPT3DVisuProvider& operator=(JDAPT3DVisuProvider&);

};

//-----------------------------------------------------------------------

#endif
