set #envTSLOGSHELLEXT1232=364524176
set ADL_DB2INSTANCE=DB2
set ADL_DFLT_RULES_LIB=ADLCMCNextArchiRules
set ADL_DIFF_LOCAL=N
set ADL_DIFF_PATH=N/A
set ADL_MERGER="C:\WinhoMBE\DassaultSystemes\V5R18\T18\intel_a\code\command\ADLMerger2.bat"
set ADL_NLS_LANG=AMERICAN_AMERICA.WE8ISO8859P1
set ADL_ORA_TNS_ADMIN=NA
set ADL_PATH=C:\WinhoMBE\DassaultSystemes\V5R18\T18\intel_a
set ADL_SITE_NAME=V5R18_B18
set ADL_TMP=C:\TEMP
set ADL_USER_PATH=C:\WinhoMBE\DassaultSystemes\V5R18\T18\intel_a\code\command
set ADSK_3DSMAX_x64_2018=C:\WinhoMBE\Autodesk\3ds Max 2018\
set ADSK_CLM_WPAD_PROXY_CHECK=FALSE
set ALLUSERSPROFILE=C:\ProgramData
set APPDATA=C:\Users\Administrator\AppData\Roaming
set BLD_HOST_OS=win_b64
set CGTECH_INSTALL=C:\WinhoMBE\CGTech\VERICUT 8.0.3
set CGTECH_PRODUCTS=C:\WinhoMBE\CGTech\VERICUT 8.0.3\windows64
set CommonProgramFiles=C:\Program Files (x86)\Common Files
set CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
set CommonProgramW6432=C:\Program Files\Common Files
set COMPUTERNAME=WINHOPLM
set ComSpec=C:\Windows\system32\cmd.exe
set CorbaCppBuildROOT_PATH=\\lisa\iona\Orbix3.3\win_b64
set CorbaCppROOT_PATH=\\lisa\iona\Orbix3.3\win_b64
set CorbaJavaROOT_PATH=\\lisa\iona\Orbix3.3\win_b64
set CSCSkipTestOfMapFileValidity=1
set DSarMakerROOT_PATH=C:\WinhoMBE\DASSAU~1\V5R18\T18\CATWebDSarMaker
set FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
set FPS_BROWSER_USER_PROFILE_STRING=Default
set HOMEDRIVE=C:
set HOMEPATH=\Users\Administrator
set INCLUDE=C:\WinhoMBE\DASSAU~1\V5R18\T18\intel_a\tools\include\win_b64;C:\WinhoMBE\DASSAU~1\V5R18\T18\intel_a\tools\include;C:\Program Files (x86)\Microsoft Visual Studio 8\VC\include;C:\Program Files (x86)\Microsoft Visual Studio 8\VC\atlmfc\include;C:\Program Files (x86)\Microsoft Visual Studio 8\VC\PlatformSDK\include
set Java1ROOT_PATH=C:\jdk1.1.8
set Java3ROOT_PATH=C:\jdk1.3.1_08
set JLMDeployROOT_PATH=C:\WinhoMBE\DASSAU~1\V5R18\T18\intel_a\jlm\jlmdeploy65
set LIB=C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.0;C:\Program Files (x86)\Microsoft Visual Studio 8\VC\lib\amd64;C:\Program Files (x86)\Microsoft Visual Studio 8\VC\atlmfc\lib\amd64;C:\Program Files (x86)\Microsoft Visual Studio 8\VC\PlatformSDK\lib\amd64
set LOCALAPPDATA=C:\Users\Administrator\AppData\Local
set LOGONSERVER=\\WINHOPLM
set LSERVOPTS=-s C:\ProgramData\CGTech\license\cgtech.lf
set LSHOST=localhost
set mkcsClientMode=1
set mkcsOS_Buildtime=intel_a
set mkcsOS_NAME=Windows_NT
set mkcsOS_Runtime=intel_a
set mkcsROOT_PATH=C:\WinhoMBE\DASSAU~1\V5R18\T18\intel_a
set mkcsSHLIB_NAME=PATH
set mkcsSHLIB_PATH=C:\WinhoMBE\DASSAU~1\V5R18\T18\intel_a\code\bin
set MkmkADDON_LEVEL=MK_ORBIXCPP33 MK_ORBIXJAVA33 MK_MSCVER=1400
set MkmkADDON_LIB=C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.0;C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set MkmkADDON_PATH=C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set MkmkASPNET20Internal=yes
set mkmkbuild=21803
set MkmkDictionary_PATH=C:\WinhoMBE\DASSAU~1\V5R18\T18\intel_a\code\dictionary
set MkmkIC_PATH=C:\WinhoMBE\DASSAU~1\V5R18\T18\intel_a\code\productIC
set MkmkIF60=yes
set MkmkIF60Internal=yes
set MkmkIF90Internal=yes
set MkmkINSTALL_PATH=C:\WinhoMBE\DASSAU~1\V5R18\T18
set MkmkMsgCatalog_PATH=C:\WinhoMBE\DASSAU~1\V5R18\T18\intel_a\resources\msgcatalog
set MkmkMSNET30DIR=C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.0
set MkmkMSVCADDON_INCLUDE_80=C:\Program Files (x86)\Microsoft Visual Studio 8\VC\include;C:\Program Files (x86)\Microsoft Visual Studio 8\VC\atlmfc\include;C:\Program Files (x86)\Microsoft Visual Studio 8\VC\PlatformSDK\include
set MkmkMSVCADDON_LIB_80=C:\Program Files (x86)\Microsoft Visual Studio 8\VC\lib\amd64;C:\Program Files (x86)\Microsoft Visual Studio 8\VC\atlmfc\lib\amd64;C:\Program Files (x86)\Microsoft Visual Studio 8\VC\PlatformSDK\lib\amd64
set MkmkMSVCADDON_PATH_80=C:\Program Files (x86)\Microsoft Visual Studio 8\VC\bin\amd64
set MkmkMSVCDIR=C:\Program Files (x86)\Microsoft Visual Studio 8\VC
set MkmkMSVCDIR_80=C:\Program Files (x86)\Microsoft Visual Studio 8\VC
set MkmkMSVCSHARPDIR=C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set MkmkMSVJSHARPDIR=C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set MkmkMSVSADDON_PATH_80=C:\Program Files (x86)\Microsoft Visual Studio 8\Common7\Tools\Bin;C:\Program Files (x86)\Microsoft Visual Studio 8\Common7\IDE
set MkmkMSVSBINDIR=C:\Program Files (x86)\Microsoft Visual Studio 8\Common7\IDE
set MkmkOrbixCpp33=yes
set MkmkOrbixCpp33Internal=yes
set MkmkOrbixJava33=yes
set MkmkOrbixJava33Internal=yes
set MkmkOS_BitMode=64
set MkmkOS_Buildtime=win_b64
set MkmkOS_DOC=DOC
set MkmkOS_NAME=Windows_NT
set MkmkOS_Runtime=intel_a
set MkmkOS_Type=Windows
set MkmkOS_VAR=win_b64
set MkmkReffiles_PATH=C:\WinhoMBE\DASSAU~1\V5R18\T18\intel_a\reffiles
set MkmkRMSSDK_PATH=C:\WinhoMBE\DASSAU~1\V5R18\T18\intel_a\.\rms\rmssdksp2
set MkmkROOT_PATH=C:\WinhoMBE\DASSAU~1\V5R18\T18\intel_a
set MkmkSHLIB_NAME=Path
set MkmkSHLIB_PATH=C:\WinhoMBE\DASSAU~1\V5R18\T18\intel_a\code\bin
set mkmkvers=mkmk Version 2.18.3
set MkmkVERSIONINFO=NO
set MkmkVS60=yes
set MkmkVS60Internal=yes
set MkmkVS80Internal=yes
set MkmkXMLMANIFEST=NO
set MKMK_JAVAC_CMD_SIZE=32000
set Mkmk_Modifier=1034
set MKMK_NO_MONOCODE_DOC=yes
set MKMK_USEPRECOMPIL=yes
set MkodtOS_Runtime=win_b64
set MK_DEVNULL=NUL
set MK_SEPARATOR=\;
set MK_TEMPDIR=C:\temp
set NLS_LANG=SIMPLIFIED CHINESE_CHINA.ZHS16GBK
set NO_LOCAL_DEFINITION_FOR_IID=yes
set NTsetenvPath=C:\WinhoMBE\DASSAU~1\V5R18\T18\intel_a\code\command\
set NUMBER_OF_PROCESSORS=4
set OneDrive=C:\Users\Administrator\OneDrive
set OS=Windows_NT
set OSMFEATROOT_PATH="\\atlas\tools\osmfeat\osmfeat\"
set PATH=C:\Program Files (x86)\Microsoft Visual Studio 8\VC\bin\amd64;C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.0;C:\Windows\Microsoft.NET\Framework64\v2.0.50727;C:\Program Files (x86)\Microsoft Visual Studio 8\Common7\Tools\Bin;C:\Program Files (x86)\Microsoft Visual Studio 8\Common7\IDE;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\Oracle\Java\javapath;C:\WinhoDevSoftwares\DataBase\Oracle\product\11.2.0\dbhome_1\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Common Files\Autodesk Shared\;C:\Program Files (x86)\Autodesk\Backburner\;C:\Program Files (x86)\Common Files\Acronis\SnapAPI\;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\WinhoMBE\DassaultSystemes\V5R18\T18\intel_a\TCK\command;C:\WinhoMBE\DASSAU~1\V5R18\T18\intel_a\code\command;C:\WinhoMBE\DASSAU~1\V5R18\T18\intel_a\code\command;C:\WinhoMBE\DassaultSystemes\V5R18\T18\intel_a\code\command
set PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
set PROCESSOR_ARCHITECTURE=x86
set PROCESSOR_ARCHITEW6432=AMD64
set PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
set PROCESSOR_LEVEL=6
set PROCESSOR_REVISION=4e03
set PROG27B48B2C053=1
set ProgramData=C:\ProgramData
set ProgramFiles=C:\Program Files (x86)
set ProgramFiles(x86)=C:\Program Files (x86)
set ProgramW6432=C:\Program Files
set PROMPT=$P$G
set PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
set PUBLIC=C:\Users\Public
set RADECATSettingPath=C:\Users\Administrator\AppData\Roaming\DassaultSystemes\RADE
set RELEASEMANAGER_PATH=C:\WinhoMBE\DASSAU~1\V5R18\T18\intel_a
set rtcode=0
set SESSIONNAME=Console
set SPLM_LICENSE_SERVER=27800@localhost
set SystemDrive=C:
set SystemRoot=C:\Windows
set TCKHelp=-
set TCKOS_Runtime=intel_a
set TCK_DATE=2018/05/04-18:08:41
set TCK_ID=V5R18_B18
set TCK_INSTALL_PATH=C:\WinhoMBE\DassaultSystemes\V5R18\T18
set TCK_LOCAL_INFO=C:\Program Files (x86)
set TCK_NAME=V5R18_B18
set TCK_NO_SERVER=true
set TCK_ROOT_PATH=C:\WinhoMBE\DassaultSystemes\V5R18\T18\intel_a
set TCK_TMP_FILE=C:\Users\ADMINI~1\AppData\Local\Temp\tckexec__Administrator_23777.bat
set TEMP=C:\Users\ADMINI~1\AppData\Local\Temp
set TMP=C:\Users\ADMINI~1\AppData\Local\Temp
set TMPFILE=\adl_unset_30085.bat
set UGII_BASE_DIR=C:\WinhoMBE\Siemens\NX 12.0
set UGII_LANG=simpl_chinese
set USERDOMAIN=WINHOPLM
set USERDOMAIN_ROAMINGPROFILE=WINHOPLM
set USERNAME=Administrator
set USERPROFILE=C:\Users\Administrator
set VBTtmp=C:\Users\ADMINI~1\AppData\Local\Temp
set VS80COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 8\Common7\Tools\
set VS90COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\Tools\
set WecVersionForRosebud.3598=2
set windir=C:\Windows
set _tck_exec=OK
set __COMPAT_LAYER=ElevateCreateProcess
