// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// SJDPartExampleCmd.h
// The state chart based command: SJDPartExampleCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   STATECOMMAND
//End CAA2 Wizard Generation Report
//
//  Jan 2015  Creation: Code generated by the CAA wizard  LuJunHome
//===================================================================
#ifndef SJDPartExampleCmd_H
#define SJDPartExampleCmd_H

#include "CATStateCommand.h"
#include "CATBoolean.h"
#include "CATDialogAgent.h"
#include "CAT3DRep.h"
#include "CATUnicodeString.h"

#include "SJDPartExampleDlg.h"

//----------------------------------------------------------------------

/**
 * Describe your command here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog engine framework.
 * (consult base class description).
 */
class SJDPartExampleCmd: public CATStateCommand
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( SJDPartExampleCmd, CATStateCommand )

  public:

  SJDPartExampleCmd();
  virtual ~SJDPartExampleCmd();

    /**
     * Defines the command automata.
     * <br>
     * <i>(states, transitions and agents)</i>
     */
  virtual void     BuildGraph();

    /**
     * Action associated to state transitions.
     */
  virtual CATBoolean  ActionComboSelect(void * data);
  virtual CATBoolean  ActionOkButton(void * data);
  virtual CATBoolean  ActionCloseButton(void * data);
  virtual CATBoolean  ActionApplyButton(void * data);

  CAT3DRep *GetRepFromDocument(CATUnicodeString istrFileName);

  private:
	SJDPartExampleDlg *_pMyDlg;
	CATDialogAgent  *_pOkAgent,
					*_pApplyAgent,
					*_pCloseAgent,
					*_pWinCloseAgent,
					*_pComboSelectAgent;
	CAT3DRep *_p3DRep;
	CAT3DRep *_p3DRep1;
	CAT3DRep *_p3DRep2;
	CAT3DRep *_p3DRep3;
	CAT3DRep *_p3DRep4;
};

//----------------------------------------------------------------------

#endif
