// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// SJDPartExampleDlg.h
// The dialog : SJDPartExampleDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   DIALOG
//End CAA2 Wizard Generation Report
//
//  Jan 2015  Creation: Code generated by the CAA wizard  LuJunHome
//===================================================================
#ifndef SJDPartExampleDlg_H
#define SJDPartExampleDlg_H

#include "CATDlgDialog.h"
#include "CATDlgInclude.h"
#include "CATUnicodeString.h"

#include "CATNavigation3DViewer.h"

//----------------------------------------------------------------------

/**
 * Describe the purpose of your panel here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog framework.
 * (consult base class description).
 */
class SJDPartExampleDlg: public CATDlgDialog
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( SJDPartExampleDlg, CATDlgDialog )

  public:

  SJDPartExampleDlg();
  virtual ~SJDPartExampleDlg();

  void Build ();

    CATDlgCombo * GetCombo();

	CATNavigation3DViewer * GetViewer3D();




  protected:

  private:


//CAA2 WIZARD WIDGET DECLARATION SECTION
 CATDlgFrame*      _FrameViewer;
 CATDlgFrame*      _FrameFile;
 CATDlgLabel*      _LabelFile;
 CATDlgCombo*      _ComboFile;
//END CAA2 WIZARD WIDGET DECLARATION SECTION

 CATNavigation3DViewer *_pViewer3D;
};

//----------------------------------------------------------------------

#endif
