# COPYRIGHT Dassault Systemes 2009
#======================================================================
# Imakefile for module JDAPointInterfacesUUID.m
#======================================================================
#
#  Apr 2009  Creation: Code generated by the CAA wizard  LuJun
#======================================================================
#
# ARCHIVE
#
BUILT_OBJECT_TYPE=ARCHIVE
