// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// CATAgentServices.h
// Header definition of CATAgentServices
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Apr 2015  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#ifndef CATAgentServices_H
#define CATAgentServices_H

#include "WinhoAgentServices.h"
#include "CATBaseUnknown.h"

#include "CATPathElementAgent.h"
#include "CATISpecObject.h"
#include "CATPathElement.h"
#include "CATLISTV_CATISpecObject.h"
#include "CATFeatureImportAgent.h"
#include "CATIProduct.h"




//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* Do not use the @href CATAgentServices constructor to
* do such and such but instead...
*
* @example
*  // example is optional
*  pObject = new CATAgentServices;
*  pObject->SetXXX(...);
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class ExportedByWinhoAgentServices CATAgentServices: public CATBaseUnknown
{
  CATDeclareClass;

  public:

	  // Standard constructors and destructors
	  // -------------------------------------
		 CATAgentServices ();
		 virtual ~CATAgentServices ();

	  // Copy constructor and equal operator
	  // -----------------------------------
	  CATAgentServices (CATAgentServices &);
	  CATAgentServices& operator=(CATAgentServices&);

	  static HRESULT RetrieveSelectedObjFromMonoPathElementAgent(CATPathElementAgent * ipPathElementAgent,
																  CATISpecObject_var &ospSelectedObj,
																  CATPathElement * &opSelectedPE);

	  static HRESULT RetrieveSelectedObjsFromMultiPathElementAgent(CATPathElementAgent * ipPathElementAgent,
																	  CATLISTV(CATISpecObject_var) &ospSelectedObjList,
																	  CATBoolean iRetrievePEOrNot,
																	  CATLISTP(CATBaseUnknown) &opPathEleBUList);

	  static HRESULT RetrieveSelectedObjFromMonoFeatureImportAgent(CATFeatureImportAgent * ipFeatureImportAgent,
																   CATISpecObject_var &ospSpecObject,
																   CATIProduct_var &ospFatherPro,
																   CATUnicodeString &ostrObjName);

	  static HRESULT RetrieveSelectedObjFromMonoFeatureImportAgent2(CATFeatureImportAgent * ipFeatureImportAgent,
																    CATISpecObject_var &ospSpecObject,
																    CATIProduct_var &ospFatherPro,
																    CATUnicodeString &ostrObjName);


};

//-----------------------------------------------------------------------

#endif
