// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// CATCGMServices.h
// Header definition of CATCGMServices
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Apr 2015  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#ifndef CATCGMServices_H
#define CATCGMServices_H

#include "WinhoCGMServices.h"
#include "CATBaseUnknown.h"

#include "CATISpecObject.h"
#include "CATIPrtPart.h"
#include "CATIProduct.h"
#include "CATBody.h"
#include "CATMathBox.h"

#include "CATICGMContainer.h"

#include "CATIDatumFactory.h"

#include "CATLISTV_CATMathPoint.h"

#include "CATGeoFactory.h"
#include "CATIGSMFactory.h"

#include "CATIPrtFactory.h"
#include "ListPOfCATBody.h"








//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* Do not use the @href CATCGMServices constructor to
* do such and such but instead...
*
* @example
*  // example is optional
*  pObject = new CATCGMServices;
*  pObject->SetXXX(...);
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class ExportedByWinhoCGMServices CATCGMServices: public CATBaseUnknown
{
  CATDeclareClass;

  public:

	  // Standard constructors and destructors
	  // -------------------------------------
		 CATCGMServices ();
		 virtual ~CATCGMServices ();

	  // Copy constructor and equal operator
	  // -----------------------------------
	  CATCGMServices (CATCGMServices &);
	  CATCGMServices& operator=(CATCGMServices&);

	  static HRESULT RetrieveBodyFromSpecObject(CATISpecObject_var ispSpecObject,
												CATBody_var &ospBody);

	  static HRESULT RetrieveBodyFromFeature(CATISpecObject_var ispSpecObject,
											 CATBody_var &ospBody);

	  static HRESULT RetrieveMainBodyFromPart(CATIPrtPart_var ispPrtPart,
											  CATBody_var &ospPartMainBody);

	  static HRESULT RetrieveAllSolidBodiesFromPart(CATIPrtPart_var ispPrtPart,
													CATLISTV(CATBaseUnknown_var) &ospSolidBodyBUList);
	  
	  static HRESULT RetrieveMathBoxFromProduct(CATIProduct_var ispProduct,
												CATMathBox &oMathBox);

	  static HRESULT RetrievePersistentTagOfObj(CATISpecObject_var ispSpecObject,
												CATUnicodeString &ostrPersistentTag);

	  static HRESULT RetrieveObjByPersistentTag(CATIPrtPart_var ispPrtPart,
												CATUnicodeString istrPersistentTag,
												CATISpecObject_var &ospSpecObject);

	  static HRESULT RetrieveCGMContainerFromPart(CATIPrtPart_var ispPrtPart,
												  CATICGMContainer * &opCGMContainer);

	  static HRESULT RetrieveDatumFactoryFromPart(CATIPrtPart_var ispPrtPart,
												  CATIDatumFactory_var &ospDatumFactory);

	  static HRESULT TessellatePartSurface(CATIPrtPart_var ispPart,
										   CATLISTV(CATMathPoint) &oTessellatedPtList);

	  static HRESULT TessellateWire(CATBody_var ispWireBody,
									CATLISTV(CATMathPoint) &oTessellatedPtList);

	  static HRESULT RetrieveGeoFactoryOfPart(CATIPrtPart_var ispPart,
											  CATGeoFactory_var &ospGeoFactory);

	  static HRESULT RetrieveGSMFactoryOfPart(CATIPrtPart_var ispPart,
											  CATIGSMFactory_var &ospGSMFactory);

	  static HRESULT RetrievePrtFactoryOfPart(CATIPrtPart_var ispPart,
										      CATIPrtFactory_var &ospPrtFactory);


	  static HRESULT UpdateObjWithoutMessage(CATISpecObject_var iospObjToUpdate);

	  static HRESULT DeleteFeature(CATBaseUnknown_var &iospFeatureToDelete);

	  static HRESULT CreateDatumFromFeature(CATISpecObject_var ispRefFeaturObj,
											CATISpecObject_var &ospNewFeaturObj);

	  static HRESULT CreateDatumFromBody(CATBody_var ispBody,
										 CATIPrtPart_var ispPart,
										 CATISpecObject_var &ospNewFeaturObj);

	  static HRESULT RetrieveAllSurfaceObjsFromPart(CATIPrtPart_var ispPart,
													CATLISTV(CATISpecObject_var) &ospSurfObjList);

	  static CATBoolean IsTwoObjsEqualBasedOnPersistentTag(CATISpecObject_var ispObject1,
														   CATISpecObject_var ispObject2);

	  static HRESULT RetrieveBoundaryLoopOfFace(CATBody * ipFaceBody,
											    CATGeoFactory_var ispGeoFactoryOfPart,
											    CATBody_var &ospBoundaryLoopBody);

	  static HRESULT RetrieveCenterNormalVectorOfFace(CATBody_var ispFaceBody,
													  CATMathVector &oNormalVector);


	  static HRESULT CreateEmptyBodyInPart(CATIPrtPart_var ispPart,
										   CATBody_var &ospBody);

	  static HRESULT UniteBodys(CATBody_var ispBodyToUnite,
								CATBody_var &iospResultBody,
								int iiDimension = int(-1));

	  //获取点到曲面的投影点
	  static HRESULT RetrieveProjPtOfPtToSurf(CATGeoFactory_var ispGeoFactory, 
												 CATTopData iTopData, 
												 CATBody_var ispPtBody,
												 CATBody_var ispSurfBody,
												 CATMathPoint &oProjPt,
												 CATBody_var &ospProjPtBody);

	  //在输入的曲面对象列表中，识别与指定曲面相连接的曲面对象。（法向量夹角超过30度认为不连接）
	  static HRESULT RecogniseConjointSurfaces();

	  //static HRESULT ProjectCurveToLoopSurface();
	  //计算曲线在毛坯侧表面投影信息
	  static HRESULT RetrieveProjectCurveBodyOnBlankSideSurf(CATGeoFactory_var ispGeoFactory, 
														     CATBody_var ispCurvebody,
															 CATLISTP(CATBody) ipSideSurfBodyList,
															 CATBody_var ispMachinedPrtBody,
															 CATMathVector iRefNormalVector,
															 CATBody_var &ospProjCurveBody,
															 CATISpecObject_var ispGSObj,
															 CATIPrtPart_var ispPart);

	  static HRESULT CreateCurveByPtsOnBlankSideSurf(CATGeoFactory_var ispGeoFactory, 
												     CATTopData iTopData, 
												     CATBody_var ispSurfBody,
												     CATLISTV(CATMathPoint) iPtList,
													 CATLISTP(CATBody) ipPtBodyList,
													 CATMathVector iRefNormalVector,
													 CATBody_var &ospCurveBody,
													 CATISpecObject_var ispGSObj,
													 CATIPrtPart_var ispPart);

	  static HRESULT CreateExtremityPtOnBlankSideSurf(CATGeoFactory_var ispGeoFactory, 
													  CATTopData iTopData, 
													  CATBody_var ispSurfBody,
													  CATBody_var ispRefPtBody,
													  CATMathPoint iRefPt,
													  CATMathVector iRefNormalVector,
													  CATBody * &opExtremityPtBody,
													  CATISpecObject_var ispGSObj,
													  CATIPrtPart_var ispPart);

	  static HRESULT RetrieveTopAssembleBody(CATGeoFactory_var ispGeoFactory, 
											 CATTopData iTopData, 
											 ListPOfCATBody ipBodyList,
											 CATBody_var &ospAssembleBody);

	  static HRESULT CopyBodyToSpecPart(CATBody_var ispBodyToCopy,
									    CATIPrtPart_var ispSourcePrtPart,
									    CATIProduct_var ispSourcePartPro,
									    CATIPrtPart_var ispTargetPrtPart,
									    CATIProduct_var ispTargetPartPro,
									    CATISpecObject_var &ospCopyResultObj,
									    CATBody_var &ospBodyOfCopyResultObj);

	  


};

//-----------------------------------------------------------------------

#endif
