// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// CATDocServices.h
// Header definition of CATDocServices
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Apr 2015  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#ifndef CATDocServices_H
#define CATDocServices_H

#include "WinhoDocServices.h"
#include "CATBaseUnknown.h"

#include "CATUnicodeString.h"
#include "CATDocument.h"

#include "CATIProduct.h"



//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* Do not use the @href CATDocServices constructor to
* do such and such but instead...
*
* @example
*  // example is optional
*  pObject = new CATDocServices;
*  pObject->SetXXX(...);
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class ExportedByWinhoDocServices CATDocServices: public CATBaseUnknown
{
  CATDeclareClass;

  public:

	  // Standard constructors and destructors
	  // -------------------------------------
		 CATDocServices ();
		 virtual ~CATDocServices ();

	  // Copy constructor and equal operator
	  // -----------------------------------
	  CATDocServices (CATDocServices &);
	  CATDocServices& operator=(CATDocServices&);

	  static HRESULT NewDocByIniInteractiveSession(CATUnicodeString istrDocType,
												   CATDocument * &opDocument);

	  static HRESULT OpenDocByIniInteractiveSession(CATUnicodeString istrStorageName,
													CATDocument * &opDocument);

	  static HRESULT RetrieveDocumentFromProduct(CATIProduct_var ispProduct,
												 CATDocument * &opDocument);

	  static HRESULT SaveDocumentByVBA(CATDocument * ipDocToSave);

	  static HRESULT SaveDocumentByVBA(CATUnicodeString istrDocFullPath);

	  static HRESULT SaveDocument(CATUnicodeString istrDocFullPath,
								  CATUnicodeString istrFormat = CATUnicodeString(""));

	  static HRESULT SaveDocument(CATDocument * ipDocToSave);

	  static HRESULT SaveDocumentAsNew(CATDocument * ipDocToSave,
									   CATUnicodeString istrNewDocStorageName);

	  static HRESULT CloseDocumentInIniInteractiveSession(CATUnicodeString istrStorageName);


};

//-----------------------------------------------------------------------

#endif
