// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// CATPPRServices.h
// Header definition of CATPPRServices
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Apr 2015  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#ifndef CATPPRServices_H
#define CATPPRServices_H

#include "WinhoPPRServices.h"
#include "CATBaseUnknown.h"

#include "CATISPPActivityRoot.h"
#include "CATDocument.h"
#include "CATUnicodeString.h"
#include "CATLISTV_CATISpecObject.h"
#include "CATISPPActivity.h"
#include "CATISPPAbstractActivity.h"
#include "CATIProduct.h"
#include "CATPathElement.h"
#include "CATIPrtPart.h"
#include "CAT4x4Matrix.h"
#include "CATMathTransformation.h"
#include "CATISpecAttrKey.h"
#include "CATISpecAttrAccess.h"
//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* Do not use the @href CATPPRServices constructor to
* do such and such but instead...
*
* @example
*  // example is optional
*  pObject = new CATPPRServices;
*  pObject->SetXXX(...);
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class ExportedByWinhoPPRServices CATPPRServices: public CATBaseUnknown
{
  CATDeclareClass;
  
  public:

	  // Standard constructors and destructors
	  // -------------------------------------
		 CATPPRServices ();
		 virtual ~CATPPRServices ();

	  // Copy constructor and equal operator
	  // -----------------------------------
	  CATPPRServices (CATPPRServices &);
	  CATPPRServices& operator=(CATPPRServices&);

	  static HRESULT RetrieveRootActivity(CATISPPActivityRoot_var &ospRootActivity,
										  CATDocument * ipPPRDoc = NULL);

	  static HRESULT AddRootActivity(CATISPPActivityRoot_var &ospNewRootAct,
									  CATDocument * ipPPRDoc = NULL,
									  CATUnicodeString istrActLabel = CATUnicodeString(""),
									  CATUnicodeString istrActIcon = CATUnicodeString(""));

	  static HRESULT RetrieveAllActivities(CATLISTV(CATISpecObject_var) &ospActivityObjList,
										   CATDocument * ipProcessDoc = NULL);

	  static HRESULT RetrieveDirActivitiesFromFatherActObj(CATISpecObject_var ispFatherActObj,
															CATLISTV(CATISpecObject_var) &ospActivityObjList);

	  static HRESULT RetrieveSpecActsFromHSOByHiddenAttr(CATUnicodeString istrAttrKey,
														  CATUnicodeString istrAttrValue,
														  CATLISTV(CATISpecObject_var) &ospSpecActObjList);

	  static HRESULT RetrieveSpecActsByHiddenAttr(CATUnicodeString istrAttrKey,
												  CATUnicodeString istrAttrValue,
												  CATLISTV(CATISpecObject_var) &ospSpecActObjList,
												  CATDocument * ipProcessDoc = NULL);

	  static HRESULT RetrieveSpecActsByHiddenAttrFromFatherAct(CATISPPActivity_var ispFatherAct,
																  CATUnicodeString istrAttrKey,
																  CATUnicodeString istrAttrValue,
																  CATLISTV(CATISpecObject_var) &ospSpecActObjList);

	  static HRESULT RetrieveAttrValuesFromAct(CATISPPActivity_var ispActivity,
												  CATLISTV(CATUnicodeString) istrAttrNameList,
												  CATLISTV(CATUnicodeString) &ostrAttrValueList);

	  static HRESULT SetAttrValuesForAct(CATISPPActivity_var ispActivity,
										  CATLISTV(CATUnicodeString) istrAttrNameList,
										  CATLISTV(CATUnicodeString) istrAttrValueList);

	  static HRESULT AddChildActToSpecFatherAct(CATISPPAbstractActivity_var ispFatherAct,
												CATISPPAbstractActivity_var &ospChildAct,
												CATISPPAbstractActivity_var ispPreAct = NULL_var);

	  static HRESULT RetrieveStartAndStopActsFromSpecFatherAct(CATISPPAbstractActivity_var ispFatherAct,
																  CATISPPAbstractActivity_var &ospStartAct,
																  CATISPPAbstractActivity_var &ospStopAct);

	  static HRESULT SetActivitiesFlow(CATISPPAbstractActivity_var ispFatherAct,
									   CATISPPAbstractActivity_var ispPreAct = NULL_var);

	  static HRESULT UpActFlow(CATISPPAbstractActivity_var ispAct,
								CATISPPAbstractActivity_var ispFatherAct = NULL_var);

	  static HRESULT RemoveChildActFromSpecFatherAct(CATISPPAbstractActivity_var ispChildAct,
														CATISPPAbstractActivity_var ispFatherAct = NULL_var);

	  static HRESULT RetrieveDirProsFromProductList(CATLISTV(CATISpecObject_var) &ospDirProObjList);

	  static HRESULT RetrieveDirProsFromPPRDoc(CATDocument * ipPPRDoc,
												CATLISTV(CATISpecObject_var) &ospDirProObjList);

	  static HRESULT RetrieveDirProsFromResourcesList(CATLISTV(CATISpecObject_var) &ospDirRscProObjList);

	  static HRESULT RetrieveDirProcessesFromPPR(CATLISTV(CATISpecObject_var) &ospProcessObjList);

	  static HRESULT RetrieveDirProsFromProductListAndResourcesList(CATLISTV(CATISpecObject_var) &ospDirProObjList,
																	CATLISTV(CATISpecObject_var) &ospDirRscProObjList);

	  static HRESULT RetrieveSpecProcessByLabel(CATUnicodeString istrProcLabel,
												CATBaseUnknown_var &ospProcBU);

	  static HRESULT RetrieveTopObjsInPPR(CATLISTV(CATISpecObject_var) &ospTopObjList);

	  static HRESULT AddProductToProductList(CATDocument * ipPPRDoc,
												CATIProduct_var ispRootProToAdd);

	  static HRESULT RemoveProductFromProductList(CATDocument * ipPPRDoc,
												  CATIProduct_var ispRootProToRemove);

	  static CATBoolean IsProInProductList(CATISpecObject_var ispProObj,
											CATLISTV(CATISpecObject_var) ispDirProObjList);

	  static CATBoolean IsProInResourcesList(CATISpecObject_var ispProObj,
												CATLISTV(CATISpecObject_var) ispDirRscProObjList);

	  static HRESULT RetrieveItemsFromActObj(CATISpecObject_var ispActObj,
											 CATLISTV(CATISpecObject_var) &ospItemObjList);
	  static HRESULT AddItemsToActObj(CATISpecObject_var ispActObj,
									  CATLISTV(CATISpecObject_var) ispItemObjList);

	  static HRESULT RetrieveResourcesFromActObj(CATISpecObject_var ispActObj,
												 CATLISTV(CATISpecObject_var) &ospResourceObjList);
	  static HRESULT AddResourcesToActObj(CATISpecObject_var ispActObj,
										  CATLISTV(CATISpecObject_var) ispResourceObjList);

	  static HRESULT RetrieveSpecParamsFromProObj(CATISpecObject_var ispProObj,
												  CATLISTV(CATUnicodeString) istrParamNameList,
												  CATLISTV(CATUnicodeString) &ostrParamValueList);

	  static HRESULT RetrieveInstProFromPathElement(CATPathElement * ipPathElement,
													CATIProduct_var &ospInstPro);

	  static HRESULT RetrievePartFromPrtPro(CATIProduct_var spPrtPro,
										    CATIPrtPart_var &ospPart);

	  static HRESULT RetrievePrtPartFromDoc(CATDocument * ipDocument,
											CATIPrtPart_var &ospPrtPart);

	  static HRESULT RetrievePrtPartFromDoc(CATUnicodeString istrDocStorageName,
											CATIPrtPart_var &ospPrtPart);

	  static HRESULT RetrieveRootProOfDocument(CATDocument * pDocument,
												CATIProduct_var &ospRootProduct);

	  static HRESULT RetrieveRootProFromPrtPart(CATIPrtPart_var ispPart,
												CATIProduct_var &ospRootProduct);

	  static HRESULT InsertProComponentInFatherPro(CATIProduct_var ispFatherPro,
													  CATUnicodeString &iostrProCompPartNum,
													  CATUnicodeString &iostrProCompInstNum,
													  CATIProduct_var &ospProComp);
	  static HRESULT InsertProComponentInFatherPro(CATIProduct_var ispFatherPro,
													  CATIProduct_var ispCompRefPro,
													  CATUnicodeString &iostrProCompPartNum,
													  CATUnicodeString &iostrProCompInstNum,
													  CATIProduct_var &ospProComp);


	  static HRESULT RetrieveSpecObjByNameAndTypeFromFatherObj(CATISpecObject_var ispFatherObj,
																  CATUnicodeString istrTargetObjName,
																  CATUnicodeString istrTargetObjType,
																  CATISpecObject_var &ospTargetObj);

	  static CATUnicodeString RetrieveProType(CATIProduct_var ispProduct); 


	  static HRESULT RetrieveTransformMatrixBetweenMTs(CATMathTransformation iSourceMT,
														  CATMathTransformation iTargetMT,
														  CATMathTransformation &oTransformMT);

	  static HRESULT RetrieveCurrentDocument(CATDocument * &opDocument);

	  static HRESULT RetrieveDocumentFromProduct(CATIProduct_var ispProduct,
												 CATDocument * &opDocument);

	  static HRESULT RetrieveDocumentFromPart(CATIPrtPart_var ispPrtPart,
											  CATDocument * &opDocument);

	  static HRESULT RetrieveCurrentDocType(CATUnicodeString &ostrDocType);

	  static void RetrieveMathTransformationFrom4x4Matrix(CAT4x4Matrix iMatrix,
															CATMathTransformation &oResultMT);


	  static HRESULT SetHiddenStringAttrToObj(CATISpecObject_var ispObj,
											  CATUnicodeString istrAttrKey,
											  CATUnicodeString istrAttrValue);

	  static HRESULT GetHiddenStringAttrFromObj(CATISpecObject_var ispObj,
												  CATUnicodeString istrAttrKey,
												  CATUnicodeString &ostrAttrValue);

	  static HRESULT SetHiddenIntAttrToObj(CATISpecObject_var ispObj,
										   CATUnicodeString istrAttrKey,
										   int iiAttrValue);

	  static HRESULT GetHiddenIntAttrFromObj(CATISpecObject_var ispObj,
											  CATUnicodeString istrAttrKey,
											  int &oiAttrValue);

	  /*static HRESULT SetHiddenExternalAttrToObj(CATISpecObject_var ispObj,
										        CATUnicodeString istrAttrKey,
										        CATBaseUnknown_var ispAttrValue);

	  static HRESULT GetHiddenExternalAttrFromObj(CATISpecObject_var ispObj,
											      CATUnicodeString istrAttrKey,
											      CATBaseUnknown_var &ospAttrValue);

	  static HRESULT SetHiddenComponentAttrToObj(CATISpecObject_var ispObj,
											     CATUnicodeString istrAttrKey,
											     CATBaseUnknown_var ispAttrValue);

	  static HRESULT GetHiddenComponentAttrFromObj(CATISpecObject_var ispObj,
												   CATUnicodeString istrAttrKey,
												   CATBaseUnknown_var &ospAttrValue);*/

	  static HRESULT SetHiddenStringListAttrToObj(CATISpecObject_var ispObj,
												  CATUnicodeString istrAttrKey,
												  CATLISTV(CATUnicodeString) istrAttrValueList);

	  static HRESULT GetHiddenStringListAttrFromObj(CATISpecObject_var ispObj,
													  CATUnicodeString istrAttrKey,
													  CATLISTV(CATUnicodeString) &ostrAttrValueList);

	  static HRESULT SetHiddenObjAttrToObj(CATISpecObject_var ispObj,
											  CATUnicodeString istrAttrKey,
											  CATISpecObject_var ispAttrValueObj);

	  static HRESULT GetHiddenObjAttrFromObj(CATISpecObject_var ispObj,
											  CATUnicodeString istrAttrKey,
											  CATISpecObject_var &ospAttrValueObj);

	  static HRESULT SetHiddenObjListAttrToObj(CATISpecObject_var ispObj,
												  CATUnicodeString istrAttrKey,
												  CATLISTV(CATISpecObject_var) ispAttrValueObjList);

	  static HRESULT GetHiddenObjListAttrFromObj(CATISpecObject_var ispObj,
												  CATUnicodeString istrAttrKey,
												  CATLISTV(CATISpecObject_var) &ospAttrValueObjList);

	  static HRESULT RemoveSpecHiddenAttr(CATISpecObject_var ispObj,
										  CATUnicodeString istrAttrKey);

	  static HRESULT RetrievePathElemnetFromObj(CATISpecObject_var ispObjectToExtracted,
												  CATPathElement * &opPathElement,
												  CATPathElement * ipFatherPathElement = NULL,
												  CATBoolean iIsInPPROrNot = FALSE,
												  CATLISTV(CATISpecObject_var) ispPPRTopObjList = NULL);

	  static HRESULT RetrieveFullPathOfSpePE(CATPathElement * ipPathElement,
												CATUnicodeString &ostrFullPath);

	  static HRESULT RetrieveStorageNameOfProduct(CATIProduct_var ispProduct,
												  CATUnicodeString &ostrStorageName);

	  static HRESULT AddSubNodeToSpecProInPPR(CATIProduct_var ispParentPro,
											  CATUnicodeString istrSubNodeDir);

	  static HRESULT AddSubNodesToSpecProInPPR(CATIProduct_var ispParentPro,
											   CATLISTV(CATUnicodeString) istrSubNodeDirList);

	  static HRESULT RetrieveProFullPath(CATIProduct_var ispInstPro,
										 CATUnicodeString &ostrFullPath);

	  static HRESULT RetrieveObjFullPathInPart(CATISpecObject_var ispObj,
											   CATUnicodeString &ostrFullPath);

	  static HRESULT GetPartNumber(CATIProduct_var ispProduct,
								   CATUnicodeString &ostrPartNumber);

	  static HRESULT ChangeInstNumForProInProductList(CATUnicodeString istrOldInstNum,
													  CATUnicodeString istrNewInstNum);

	  static HRESULT RetrieveObjNameByVBA(CATBaseUnknown_var ispObjBU,
										  CATUnicodeString &ostrObjName);

	  static HRESULT SetPrdInstanceName(CATIProduct_var ispInstPro,
										CATUnicodeString istrInstName);

	  static void CoutHiddenAttrsOfObj(CATISpecObject_var ispSpecObject);

	  static CATUnicodeString RetrieveAttrType(CATISpecAttrKey * ipSpecAttrKey);

	  static CATUnicodeString RetrieveAttrValue(CATISpecAttrAccess_var ispSpecAttrAccess,
											    CATISpecAttrKey * ipSpecAttrKey,
											    CATUnicodeString istrAttrType);

	  static HRESULT ReplaceChildrenPathOfProduct(CATIProduct_var ispParentPro,
												  CATUnicodeString istrOldDataFolderDir,
												  CATUnicodeString istrNewDataFolderDir);

	  static HRESULT RemoveAllChildrenFromParentPro(CATIProduct_var ispParentPro);

	  static CATUnicodeString RetrieveNomenclatureFromProduct(CATIProduct_var ispProduct);

	  static HRESULT SetProductRepresentation(CATIProduct_var ispProduct,
											  CATUnicodeString istrMode = CATUnicodeString("Design"));

	  static HRESULT ReplaceComponentsForProduct(CATUnicodeString istrProductPath);

	  static HRESULT ReplaceComponentsForProduct(CATIProduct_var ispFatherPro,
												 CATLISTV(CATUnicodeString) istrChildProPathList);

	  static HRESULT ReplaceComponentsForAsmPPProduct(CATIProduct_var ispProduct,
													  CATUnicodeString istrNewAsmPPDataFolderPath);

	  static HRESULT RemoveProduct(CATIProduct_var ispProduct);

	  static HRESULT CreateGeometricalSet(CATUnicodeString istrGSName,
										  CATISpecObject_var ispFatherObj,
										  CATISpecObject_var &ospGSObj);

	  static HRESULT SetReferencePlanesShowStateInPart(CATIPrtPart_var ispPart,
													   CATUnicodeString istrShowState = CATUnicodeString("Show"));
	  static HRESULT SetMainBodyShowStateInPart(CATIPrtPart_var ispPart,
												CATUnicodeString istrShowState = CATUnicodeString("Show"));

	  static HRESULT SetExternalReferencesGSShowStateInPart(CATIPrtPart_var ispPart,
															CATUnicodeString istrShowState = CATUnicodeString("Show"));

	  static HRESULT RetrieveMainBodyFromPart(CATIPrtPart_var ispPart,
											  CATISpecObject_var &ospMainBodyObj);

	  static HRESULT CopyObjectBetweenParts(CATISpecObject_var ispObjToCopy,
											CATIPrtPart_var ispSourcePart,
											CATIPrtPart_var ispTargetPart,
											CATISpecObject_var &ospResultObj,
											CATBoolean iKeepLink = TRUE);

	  static HRESULT CopyObjectInPart(CATISpecObject_var ispObjToCopy,
									  CATISpecObject_var ispParentObj,
									  CATISpecObject_var &ospResultObj,
									  CATBoolean iKeepLink = TRUE);


	  static HRESULT CreateParamInSpecFatherNode(CATISpecObject_var &iospFatherObj,
												 CATUnicodeString istrParamName,
												 CATUnicodeString istrParamValue);

	  static HRESULT CopySolidBodyBetweenParts(CATIPrtPart_var ispSourcePart,
											   CATIPrtPart_var ispTargetPart,
											   CATBody_var &ospResultBody);

	  static CATUnicodeString RetrieveCurrentDocumentType();
	  static CATUnicodeString RetrieveDocumentType(CATDocument * ipDocument);

	  static HRESULT SaveRootProductToSpecFolder(CATUnicodeString istrFolderPath);
	  static HRESULT SaveProductToSpecFolder(CATIProduct_var ispProduct,
											 CATUnicodeString istrFolderPath);

	  static HRESULT SaveRootProductToSpecFolderUseUUIDAsName(CATUnicodeString istrFolderPath);
	  static HRESULT SaveProductToSpecFolderUseUUIDAsName(CATIProduct_var ispProduct,
														  CATUnicodeString istrFolderPath);

	  

	  


  private:

	  static CATPathElement * RetrievePathElemnetFromObj(CATISpecObject_var ispObjectToExtracted);

	  static HRESULT CAAGsiCreateGeometricFeatureSets (const CATIContainer_var &ispCont, const CATUnicodeString& iName, 
		  const CATISpecObject_var & spInputParentTool , CATISpecObject_var & spSpecTool,  
		  int & oDiag, int iTopLevel, int iType  );

};

//-----------------------------------------------------------------------

#endif
