// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// CATVisualServices.h
// Header definition of CATVisualServices
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Apr 2015  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#ifndef CATVisualServices_H
#define CATVisualServices_H

#include "WinhoVisualServices.h"
#include "CATBaseUnknown.h"

#include "CATPathElement.h"
#include "CATISpecObject.h"
#include "CATViewer.h"
#include "CATListOfDouble.h"
#include "CAT3DViewer.h"
#include "CATNavigController.h"
#include "CATIProduct.h"
#include "CATNavigation3DViewer.h"

#include "CATIGraphNode.h"


//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* Do not use the @href CATVisualServices constructor to
* do such and such but instead...
*
* @example
*  // example is optional
*  pObject = new CATVisualServices;
*  pObject->SetXXX(...);
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class ExportedByWinhoVisualServices CATVisualServices: public CATBaseUnknown
{
  CATDeclareClass;

  public:

	  // Standard constructors and destructors
	  // -------------------------------------
		 CATVisualServices ();
		 virtual ~CATVisualServices ();

	  // Copy constructor and equal operator
	  // -----------------------------------
	  CATVisualServices (CATVisualServices &);
	  CATVisualServices& operator=(CATVisualServices&);

	  static HRESULT CleanUpHSO();

	  static HRESULT AddSpecPathElementToHSO(CATPathElement * ipPathElement);

	  static HRESULT AddObjectToHSO(CATISpecObject_var ispObject,
									  CATISpecObject_var ispFatherInstProObj = NULL_var,
									  CATBoolean iIsInPPROrNot = FALSE);

	  static HRESULT AddObjectsToHSO(CATLISTV(CATISpecObject_var) ispObjectList,
									  CATLISTV(CATISpecObject_var) ispFatherInstProObjList = NULL,
									  CATBoolean iIsInPPROrNot = FALSE);

	  static HRESULT SetSpecObjShowState(CATISpecObject_var ispSpecObject,
											CATUnicodeString istrShowOrHide);

	  static HRESULT RetrieveCurrentViewer(CATViewer * &opCurrentViewer);

	  static HRESULT ReFrameOnSpecObjIn3DViewer(CATISpecObject_var ispObject,
												  CAT3DViewer * ip3DViewer = NULL,
												  CATIProduct_var ispFatherInstPro = NULL_var);

	  static HRESULT ReFrameOnSpecObjsIn3DViewer(CATLISTV(CATISpecObject_var) ispObjectList,
												  CAT3DViewer * ip3DViewer = NULL,
												  CATLISTV(CATISpecObject_var) ispFatherInstProObjList = NULL);

	  static HRESULT RetrievePosInfoFrom3DViewer(CATListOfDouble &odPosIndoList,
													CAT3DViewer * ip3DViewer = NULL);

	  static HRESULT SetPosInfoTo3DViewer(CATListOfDouble idPosIndoList,
											CAT3DViewer * ip3DViewer = NULL);

	  static HRESULT DetachViewpointFrom3DViewer(CAT3DViewer * ip3DViewer = NULL);

	  static HRESULT ShowObjsInNvg3DViewer(CATLISTV(CATISpecObject_var) ispObjList,
											  CATNavigation3DViewer * ip3DViewer = NULL,
											  CATLISTV(CATISpecObject_var) ispFatherProObjList = NULL,
											  CATBoolean iIsInPPROrNot = FALSE);

	  static HRESULT CenterGraphInNavigGraphicWindow(CATString istrType = CATString("OnHSO"));

	  static HRESULT RetrieveNavigController(CATNavigController * &opNavigController);

	  static HRESULT ExpandTreeNodeOfSpecBU(CATBaseUnknown_var ispBaseUnknown,
											CATNavigController * ipNavigController = NULL);

	  static HRESULT RetrieveGraphNodeFromSpecBU(CATBaseUnknown_var ispBaseUnknown,
												 CATIGraphNode_var &ospGraphNode,
												 CATNavigController * ipNavigController = NULL);

	  static HRESULT SetObjectOpacity(CATISpecObject_var ispObject,
									  int iiOpacityValue);

	  static HRESULT SetObjectColor(CATISpecObject_var ispObject,
								    int iiRedValue,
								    int iiGreenValue,
									int iiBlueValue,
									CATPathElement * ipObjPE = NULL);

	  static HRESULT ResetRootNodeInNavigBox(CATBaseUnknown_var ispRootNodeBU);

	  static HRESULT RefreshTreeNode(CATBaseUnknown_var ispNodeBU);

	  static HRESULT RetrieveCATRepFromCGRFile(CATUnicodeString istrCGRFilePath,
											   CATBaseUnknown_var &ospRepBU);

	  static HRESULT RetrieveCATRepFromCGRFile(CATUnicodeString istrCGRFilePath,
											   CATRep * &opRep);

	  static HRESULT RetrieveCAT3DRepFromCGRFile(CATUnicodeString istrCGRFilePath,
											     CAT3DRep * &op3DRep);

};

//-----------------------------------------------------------------------

#endif
