// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// ENOVIAServices.h
// Header definition of ENOVIAServices
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Apr 2015  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#ifndef ENOVIAServices_H
#define ENOVIAServices_H

#include "WinhoENOVIAServices.h"
#include "CATBaseUnknown.h"
#include "CATUnicodeString.h"
#include "CATListOfCATUnicodeString.h"

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* Do not use the @href ENOVIAServices constructor to
* do such and such but instead...
*
* @example
*  // example is optional
*  pObject = new ENOVIAServices;
*  pObject->SetXXX(...);
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class ExportedByWinhoENOVIAServices ENOVIAServices: public CATBaseUnknown
{
  CATDeclareClass;

  public:

	  // Standard constructors and destructors
	  // -------------------------------------
		 ENOVIAServices ();
		 virtual ~ENOVIAServices ();

	  // Copy constructor and equal operator
	  // -----------------------------------
	  ENOVIAServices (ENOVIAServices &);
	  ENOVIAServices& operator=(ENOVIAServices&);

	  static HRESULT SaveLocalFileToENOVIAVault(CATUnicodeString istrHostName,
											    CATUnicodeString istrListenPort,
											    CATUnicodeString istrFileFullPath,
											    CATUnicodeString &ostrDocUrlInVault,
											    CATUnicodeString &ostrErrorInfo);

	  static HRESULT ReSaveLocalFileToENOVIAVault(CATUnicodeString istrHostName,
												  CATUnicodeString istrListenPort,
												  CATUnicodeString istrDocUrlInVault,
												  CATUnicodeString istrFileDir,
												  CATUnicodeString &ostrErrorInfo);

	  static HRESULT LoadDocFromENOVIAVaultByUrl(CATUnicodeString istrHostName,
											     CATUnicodeString istrListenPort,
											     CATUnicodeString istrDocUrlInVault,
											     CATUnicodeString istrFileDir,
											     CATUnicodeString &ostrErrorInfo);

	  static HRESULT LoadDocsFromENOVIAVaultByUrls(CATUnicodeString istrHostName,
												   CATUnicodeString istrListenPort,
												   CATLISTV(CATUnicodeString) istrDocUrlList,
												   CATLISTV(CATUnicodeString) istrFileDirList,
												   CATUnicodeString &ostrErrorInfo);


};

//-----------------------------------------------------------------------

#endif
