// COPYRIGHT Dassault Systemes 2009
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework JDAPointInterfaces
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Apr 2009  Creation: Code generated by the CAA wizard  LuJun
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("System",Protected);
// END WIZARD EDITION ZONE
AddPrereqComponent("ObjectModelerSystem",Protected);
AddPrereqComponent("KnowledgeInterfaces",Protected);
