// COPYRIGHT Dassault Systemes 2009
//===================================================================
//
// JDAEPTMemoAlias.h
// Provide implementation to interface
//    CATIAlias

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	JDAPTMemo
//EXTENSIONTYPE:	DataExtension

//    TIE: CATIAlias

//End CAA2 Wizard Generation Report
//
//  Apr 2009  Creation: Code generated by the CAA wizard  LuJun
//===================================================================
#ifndef JDAEPTMemoAlias_H
#define JDAEPTMemoAlias_H

#include "CATBaseUnknown.h"
#include "CATUnicodeString.h"

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href CATIAlias
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class JDAEPTMemoAlias: public CATBaseUnknown

{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     JDAEPTMemoAlias ();
     virtual ~JDAEPTMemoAlias ();

    /**
     * Implements a function from an interface.
     * @href CATIAlias#SetAlias
     */
     void SetAlias (const CATUnicodeString&  iName  ) ;

    /**
     * Implements a function from an interface.
     * @href CATIAlias#GetAlias
     */
     CATUnicodeString GetAlias () ;


  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  JDAEPTMemoAlias (JDAEPTMemoAlias &);
  JDAEPTMemoAlias& operator=(JDAEPTMemoAlias&);

};

//-----------------------------------------------------------------------

#endif
