// COPYRIGHT Dassault Systemes 2009
//===================================================================
//
// JDAEPTMemoLifeCycle.h
// Provide implementation to interface
//    LifeCycleObject

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	JDAPTMemo
//EXTENSIONTYPE:	DataExtension

//    TIE: LifeCycleObject

//End CAA2 Wizard Generation Report
//
//  Apr 2009  Creation: Code generated by the CAA wizard  LuJun
//===================================================================
#ifndef JDAEPTMemoLifeCycle_H
#define JDAEPTMemoLifeCycle_H

#include "CATSpecLifeCycleObjectExt.h"

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href LifeCycleObject
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class JDAEPTMemoLifeCycle: public CATSpecLifeCycleObjectExt

{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     JDAEPTMemoLifeCycle ();
     virtual ~JDAEPTMemoLifeCycle ();

    /**
     * Implements a function from an interface.
     * @href LifeCycleObject#remove
     */
     void remove (int  iForCloseContext =0) ;


  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  JDAEPTMemoLifeCycle (JDAEPTMemoLifeCycle &);
  JDAEPTMemoLifeCycle& operator=(JDAEPTMemoLifeCycle&);

};

//-----------------------------------------------------------------------

#endif
