// COPYRIGHT Dassault Systemes 2009
//===================================================================
//
// JDAPTNavigProvider.cpp
// Provide implementation to interface
//    CATINavigateProvider
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Apr 2009  Creation: Code generated by the CAA wizard  LuJun
//===================================================================
#include "JDAPTNavigProvider.h"
#include "CATIProduct.h"
#include "JDAIPTContainer.h"
#include "JDAIPTRoot.h"
#include "CATINavigateObject.h"
#include "CATIContainer.h"
#include "JDAIPTDocument.h"
//#include "iostream.h"
#include "CATDocument.h"
#include "CATILinkableObject.h"
#include "CATIAlias.h"
#include "CATIPrtPart.h"

#include "iostream.h"


 
CATImplementClass(JDAPTNavigProvider,
                  Implementation,
                  CATBaseUnknown,
                  CATnull );
 

//-----------------------------------------------------------------------------
// JDAPTNavigProvider : constructor
//-----------------------------------------------------------------------------
JDAPTNavigProvider::JDAPTNavigProvider():
    CATBaseUnknown()
{
}

//-----------------------------------------------------------------------------
// JDAPTNavigProvider : destructor
//-----------------------------------------------------------------------------
JDAPTNavigProvider::~JDAPTNavigProvider()
{
}
 
// Link the implementation to its interface
// ---------------------------------------



//TIE or TIEchain definitions
#include "TIE_CATINavigateProvider.h"
TIE_CATINavigateProvider(JDAPTNavigProvider);


//Methods implementation

//-----------------------------------------------------------------------------
// Implements CATINavigateProvider::GetChildren
//-----------------------------------------------------------------------------
HRESULT JDAPTNavigProvider::GetChildren (CATBaseUnknown *  iObj , CATLISTP(CATBaseUnknown) **  ioProvidedChildren)
{
	//cout <<"==> Now we are in JDAPTNavigProvider::GetChildren  !" << endl;
	HRESULT hr=E_FAIL;
	////
	//CATIAlias_var spAlias = iObj;
	//if( !!spAlias ) {
	//	cout << "  ==> (JDAPTNavigProvider) Name of object: " << spAlias->GetAlias() << endl;
	//}
	  
	//Get the document of the input object
	CATILinkableObject_var spLink = iObj;
	CATDocument *pDoc = spLink->GetDocument();

	//We display our objects only under the root product itself
	// if we are in a CATProduct document or under the MechanicalPart if
	// we are in a CATPart document
	CATBoolean isDisplayable;
	isDisplayable = false;

	if( pDoc->IsAKindOf("CATProduct") ) {
		isDisplayable = true;
		//Check that the object does not have father
		CATIProduct_var spProdObj = iObj;
		if (spProdObj != NULL_var) {
			CATIProduct_var spFatherProd = spProdObj->GetFatherProduct();
			if( spFatherProd != NULL_var) {
				CATIProduct_var spRefProduct=spProdObj->GetReferenceProduct();
				spLink = spRefProduct;
				pDoc = spLink->GetDocument();

				if( !(pDoc->IsAKindOf("CATProduct")) ) { isDisplayable = FALSE; }
			}
		}
	}

	if( pDoc && isDisplayable ) {
		//cout <<"  ==> NAVIGABLE"<<endl;
		//Retrieve annotation container
		JDAIPTDocument *piAnoDoc = NULL;
		CATIContainer *piCont = NULL;
		hr = pDoc->QueryInterface(IID_JDAIPTDocument, (void**)&piAnoDoc);
		if (SUCCEEDED(hr) && piAnoDoc) {
			hr = piAnoDoc->GetContainer(&piCont);
			piAnoDoc->Release(); piAnoDoc = NULL;
		}
		else
			cout << "  ==> Get IID_JDAIPTDocument error !"  << endl;

		//Retrieve the applicative Root object
		JDAIPTRoot *piAnoRoot = NULL;
		if (piCont) {
			//cout <<"  ==> Get document container OK !" << endl;
			JDAIPTContainer *piAnoCont = NULL;
			hr = piCont->QueryInterface (IID_JDAIPTContainer, (void**)&piAnoCont);
			//piCont->Release(); piCont = NULL;
			if (SUCCEEDED(hr) && piAnoCont) {
				//cout <<"  ==> Get JDAIPTRoot OK !" << endl;
				hr = piAnoCont->GetRoot(&piAnoRoot);
				piAnoCont->Release(); piAnoCont = NULL;
			}
			//else
				//cout << "  ==> Get IID_JDAIPTContainer error !" << endl;
		}
		//else
			//cout << "  ==> Get CATIContainer error !" << endl;

		//Add the root to the list
		if (piAnoRoot) {
			(*ioProvidedChildren) = new CATLISTP(CATBaseUnknown);
			(*ioProvidedChildren)->Append(piAnoRoot);
			hr = S_OK;
		} else {
			//cout << "  ==> Get JDAIPTRoot error !" << endl;
			hr = E_FAIL;
		}
	}
	//cout <<"==> Now end JDAPTNavigProvider::GetChildren  !" << endl;

    return hr;
}

