// COPYRIGHT Dassault Systemes 2009
//===================================================================
//
// JDAIPTContainer.h
// Define the JDAIPTContainer interface
//
//===================================================================
//
// Usage notes:
//   New interface: describe its use here
//
//===================================================================
//
//  Apr 2009  Creation: Code generated by the CAA wizard  LuJun
//===================================================================
#ifndef JDAIPTContainer_H
#define JDAIPTContainer_H

#include "JDAPointItfCPP.h"
#include "CATBaseUnknown.h"

class JDAIPTRoot;


#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByJDAPointItfCPP IID IID_JDAIPTContainer;
#else
extern "C" const IID IID_JDAIPTContainer ;
#endif

//------------------------------------------------------------------

/**
* Interface representing xxx.
*
* <br><b>Role</b>: Components that implement
* JDAIPTContainer are ...
* <p>
* Do not use the JDAIPTContainer interface for such and such

*
* @example
*  // example is optional
*  JDAIPTContainer* currentDisplay = NULL;
*  rc = window-&gt;QueryInterface(IID_JDAIPTContainer,
*                                     (void**) &amp;currentDisplay);
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class ExportedByJDAPointItfCPP JDAIPTContainer: public CATBaseUnknown
{
  CATDeclareInterface;

  public:

	  virtual HRESULT GetRoot(JDAIPTRoot **opiRoot) = 0;


    /**
     * Remember that interfaces define only virtual pure methods.
     * Dont forget to document your methods.
     * <dl>
     * <dt><b>Example:</b>
     * <pre>
     *       
           *   MyFunction does this and that
           *   @param Arg1
           *      The first argument of MyFunction.
           *   @return
           *      Error code of function.
           * 
     * virtual int MyFunction (int Arg1) = 0;
     * </pre>
     * </dl>
     */

  // No constructors or destructors on this pure virtual base class
  // --------------------------------------------------------------
};

//------------------------------------------------------------------
CATDeclareHandler(JDAIPTContainer,CATBaseUnknown);
#endif
