// COPYRIGHT Dassault Systemes 2009
//===================================================================
//
// JDAIPTDocument.h
// Define the JDAIPTDocument interface
//
//===================================================================
//
// Usage notes:
//   New interface: describe its use here
//
//===================================================================
//
//  Apr 2009  Creation: Code generated by the CAA wizard  LuJun
//===================================================================
#ifndef JDAIPTDocument_H
#define JDAIPTDocument_H

#include "JDAPointItfCPP.h"
#include "CATBaseUnknown.h"
#include "CATBoolean.h"


class CATIContainer;

#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByJDAPointItfCPP IID IID_JDAIPTDocument;
#else
extern "C" const IID IID_JDAIPTDocument ;
#endif

//------------------------------------------------------------------

/**
* Interface representing xxx.
*
* <br><b>Role</b>: Components that implement
* JDAIPTDocument are ...
* <p>
* Do not use the JDAIPTDocument interface for such and such

*
* @example
*  // example is optional
*  JDAIPTDocument* currentDisplay = NULL;
*  rc = window-&gt;QueryInterface(IID_JDAIPTDocument,
*                                     (void**) &amp;currentDisplay);
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class ExportedByJDAPointItfCPP JDAIPTDocument: public CATBaseUnknown
{
  CATDeclareInterface;

  public:

    /**
     * Remember that interfaces define only virtual pure methods.
     * Dont forget to document your methods.
     * <dl>
     * <dt><b>Example:</b>
     * <pre>
     *       
           *   MyFunction does this and that
           *   @param Arg1
           *      The first argument of MyFunction.
           *   @return
           *      Error code of function.
           * 
     * virtual int MyFunction (int Arg1) = 0;
     * </pre>
     * </dl>
     */
	  virtual HRESULT GetContainer ( CATIContainer **opiContainer,
                                   CATBoolean iCreateIfNeeded = false)=0;


  // No constructors or destructors on this pure virtual base class
  // --------------------------------------------------------------
};

//------------------------------------------------------------------
CATDeclareHandler(JDAIPTDocument,CATBaseUnknown);
#endif
