// COPYRIGHT Dassault Systemes 2009
//===================================================================
//
// JDAIPTRoot.h
// Define the JDAIPTRoot interface
//
//===================================================================
//
// Usage notes:
//   New interface: describe its use here
//
//===================================================================
//
//  Apr 2009  Creation: Code generated by the CAA wizard  LuJun
//===================================================================
#ifndef JDAIPTRoot_H
#define JDAIPTRoot_H

#include "JDAPointItfCPP.h"
#include "CATBaseUnknown.h"
#include "CATLISTV_CATBaseUnknown.h"


class CATISpecObject;

#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByJDAPointItfCPP IID IID_JDAIPTRoot;
#else
extern "C" const IID IID_JDAIPTRoot ;
#endif

//------------------------------------------------------------------

/**
* Interface representing xxx.
*
* <br><b>Role</b>: Components that implement
* JDAIPTRoot are ...
* <p>
* Do not use the JDAIPTRoot interface for such and such

*
* @example
*  // example is optional
*  JDAIPTRoot* currentDisplay = NULL;
*  rc = window-&gt;QueryInterface(IID_JDAIPTRoot,
*                                     (void**) &amp;currentDisplay);
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class ExportedByJDAPointItfCPP JDAIPTRoot: public CATBaseUnknown
{
  CATDeclareInterface;

  public:

	  virtual HRESULT AddChild (CATISpecObject *ipiFeature)=0;
	  virtual HRESULT RemoveChild (CATISpecObject *ipiFeature)=0;
	  virtual HRESULT GetChildren (const IID &iItfIID, CATListValCATBaseUnknown_var *& oList)=0;


    /**
     * Remember that interfaces define only virtual pure methods.
     * Dont forget to document your methods.
     * <dl>
     * <dt><b>Example:</b>
     * <pre>
     *       
           *   MyFunction does this and that
           *   @param Arg1
           *      The first argument of MyFunction.
           *   @return
           *      Error code of function.
           * 
     * virtual int MyFunction (int Arg1) = 0;
     * </pre>
     * </dl>
     */

  // No constructors or destructors on this pure virtual base class
  // --------------------------------------------------------------
};

//------------------------------------------------------------------
CATDeclareHandler(JDAIPTRoot,CATBaseUnknown);
#endif
