// COPYRIGHT Dassault Systemes 2009
//===================================================================
//
// JDAIPTMemoFactory.h
// Define the JDAIPTMemoFactory interface
//
//===================================================================
//
// Usage notes:
//   New interface: describe its use here
//
//===================================================================
//
//  Apr 2009  Creation: Code generated by the CAA wizard  LuJun
//===================================================================
#ifndef JDAIPTMemoFactory_H
#define JDAIPTMemoFactory_H

#include "JDAPointItfCPP.h"
#include "CATBaseUnknown.h"

class JDAIPTMemo;

#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByJDAPointItfCPP IID IID_JDAIPTMemoFactory;
#else
extern "C" const IID IID_JDAIPTMemoFactory ;
#endif

//------------------------------------------------------------------

/**
* Interface representing xxx.
*
* <br><b>Role</b>: Components that implement
* JDAIPTMemoFactory are ...
* <p>
* Do not use the JDAIPTMemoFactory interface for such and such

*
* @example
*  // example is optional
*  JDAIPTMemoFactory* currentDisplay = NULL;
*  rc = window-&gt;QueryInterface(IID_JDAIPTMemoFactory,
*                                     (void**) &amp;currentDisplay);
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class ExportedByJDAPointItfCPP JDAIPTMemoFactory: public CATBaseUnknown
{
  CATDeclareInterface;

  public:
	virtual HRESULT CreateJDAPoint(double iX,double iY,double iZ,JDAIPTMemo  **oPT) = 0;

    /**
     * Remember that interfaces define only virtual pure methods.
     * Dont forget to document your methods.
     * <dl>
     * <dt><b>Example:</b>
     * <pre>
     *       
           *   MyFunction does this and that
           *   @param Arg1
           *      The first argument of MyFunction.
           *   @return
           *      Error code of function.
           * 
     * virtual int MyFunction (int Arg1) = 0;
     * </pre>
     * </dl>
     */

  // No constructors or destructors on this pure virtual base class
  // --------------------------------------------------------------
};

//------------------------------------------------------------------
CATDeclareHandler(JDAIPTMemoFactory,CATBaseUnknown);
#endif
