D:\CurrentWork\CAAExampleProgram\SJDNavigationViewerExampleWsp\.\SJDPartExampleFrm\various\win_b64\HList\PrivateInterfaces.hl
D:\CurrentWork\CAAExampleProgram\SJDNavigationViewerExampleWsp\.\SJDPartExampleFrm\various\win_b64\HList\ProtectedInterfaces.hl
D:\CurrentWork\CAAExampleProgram\SJDNavigationViewerExampleWsp\.\SJDPartExampleFrm\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\ApplicationFrame\various\win_b64\HList\ProtectedInterfaces.hl
D:\DS\B19_64\.\ApplicationFrame\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\AutomationInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
D:\DS\B19_64\.\AutomationInterfaces\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\BatchInfrastructure\various\win_b64\HList\ProtectedInterfaces.hl
D:\DS\B19_64\.\BatchInfrastructure\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\CATDataCompatibilityInfra\various\win_b64\HList\ProtectedInterfaces.hl
D:\DS\B19_64\.\CATDataCompatibilityInfra\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\CATIADataBasics\various\win_b64\HList\ProtectedInterfaces.hl
D:\DS\B19_64\.\CATIADataBasics\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\CATJavaBridge\various\win_b64\HList\ProtectedInterfaces.hl
D:\DS\B19_64\.\CATJavaBridge\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\CATPDMBaseInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
D:\DS\B19_64\.\CATPDMBaseInterfaces\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\CATPLMDictionary\various\win_b64\HList\ProtectedInterfaces.hl
D:\DS\B19_64\.\CATPLMDictionary\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\CATTechnologicalPackageUIItf\various\win_b64\HList\ProtectedInterfaces.hl
D:\DS\B19_64\.\CATTechnologicalPackageUIItf\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\CATVirtualVaultSystem\various\win_b64\HList\ProtectedInterfaces.hl
D:\DS\B19_64\.\CATVirtualVaultSystem\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\Communications\various\win_b64\HList\ProtectedInterfaces.hl
D:\DS\B19_64\.\Communications\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\Dialog\various\win_b64\HList\ProtectedInterfaces.hl
D:\DS\B19_64\.\Dialog\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\DialogEngine\various\win_b64\HList\ProtectedInterfaces.hl
D:\DS\B19_64\.\DialogEngine\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\GSMInterfaces\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\Graph\various\win_b64\HList\ProtectedInterfaces.hl
D:\DS\B19_64\.\Graph\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\InfInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
D:\DS\B19_64\.\InfInterfaces\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\InteractiveInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
D:\DS\B19_64\.\InteractiveInterfaces\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\KnowledgeInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
D:\DS\B19_64\.\KnowledgeInterfaces\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\Mainwin\various\win_b64\HList\ProtectedInterfaces.hl
D:\DS\B19_64\.\Mainwin\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\Mathematics\various\win_b64\HList\ProtectedInterfaces.hl
D:\DS\B19_64\.\Mathematics\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\MecModInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
D:\DS\B19_64\.\MecModInterfaces\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\ObjectModelerBase\various\win_b64\HList\ProtectedInterfaces.hl
D:\DS\B19_64\.\ObjectModelerBase\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\ObjectModelerCATIA\various\win_b64\HList\ProtectedInterfaces.hl
D:\DS\B19_64\.\ObjectModelerCATIA\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\ObjectModelerCollection\various\win_b64\HList\PrivateInterfaces.hl
D:\DS\B19_64\.\ObjectModelerCollection\various\win_b64\HList\ProtectedInterfaces.hl
D:\DS\B19_64\.\ObjectModelerCollection\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\ObjectModelerInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
D:\DS\B19_64\.\ObjectModelerInterfaces\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\ObjectModelerNavigator\various\win_b64\HList\ProtectedInterfaces.hl
D:\DS\B19_64\.\ObjectModelerNavigator\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\ObjectModelerSystem\various\win_b64\HList\ProtectedInterfaces.hl
D:\DS\B19_64\.\ObjectModelerSystem\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\ObjectSpecsModeler\various\win_b64\HList\ProtectedInterfaces.hl
D:\DS\B19_64\.\ObjectSpecsModeler\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\ProductStructureInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
D:\DS\B19_64\.\ProductStructureInterfaces\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\SketcherInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
D:\DS\B19_64\.\SketcherInterfaces\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\SpecialAPI\various\win_b64\HList\ProtectedInterfaces.hl
D:\DS\B19_64\.\SpecialAPI\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\System\various\win_b64\HList\ProtectedInterfaces.hl
D:\DS\B19_64\.\System\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\VBA\various\win_b64\HList\ProtectedInterfaces.hl
D:\DS\B19_64\.\VBA\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\Visualization\various\win_b64\HList\ProtectedInterfaces.hl
D:\DS\B19_64\.\Visualization\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\VisualizationBase\various\win_b64\HList\ProtectedInterfaces.hl
D:\DS\B19_64\.\VisualizationBase\various\win_b64\HList\PublicInterfaces.hl
D:\DS\B19_64\.\XMLParser\various\win_b64\HList\ProtectedInterfaces.hl
D:\DS\B19_64\.\XMLParser\various\win_b64\HList\PublicInterfaces.hl
