# COPYRIGHT Dassault Systemes 2009
#======================================================================
# Imakefile for module JDAPTObjectView.m
#======================================================================
#
#  Apr 2009  Creation: Code generated by the CAA wizard  LuJun
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP \
JS0GROUP JS0FM ON0GREXT ON0MAIN ObjectModelerBaseUUID  \
CATVisualization CATVisUUID 
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES) CATViz CATGraphicProperties \
			CATMathematics JDAPointItf JDAPointItfCPP CATObjectSpecsModeler \
			KnowledgeItf

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
