# COPYRIGHT Dassault Systemes 2009
#======================================================================
# Imakefile for module JDAPointItfCpp.m
# Module containing the C++ source included in your interface framework
#======================================================================
#
#  Apr 2009  Creation: Code generated by the CAA wizard  LuJun
#======================================================================
#
# NO BUILD            
#

BUILT_OBJECT_TYPE=NONE
LINK_WITH = KnowledgeItf 