# COPYRIGHT Dassault Systemes 2009
#======================================================================
# Imakefile for module JDAPTCommands.m
#======================================================================
#
#  Apr 2009  Creation: Code generated by the CAA wizard  LuJun
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP \
JS0GROUP JS0FM DI0PANV2 CATMathematics CATDialogEngine  \
CATApplicationFrame  \
CATPrsWkbPrsConfiguration ProductStructureUIUUID  \
ApplicationFrame CATAfrUUID  \
CD0SCCP 
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES) CATObjectModelerBase CATObjectSpecsModeler \
			 CATPrsWkbPrsConfiguration \
			 CATApplicationFrame \
			 CATObjectModelerNavigator \
			CATProductStructure1 JDAPointItf JDAPointItfCPP CATViz CATPrsWksPRDWorkshop 

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
