set ALLUSERSPROFILE=C:\ProgramData
set APPDATA=C:\Users\ShiYi\AppData\Roaming
set BLD_HOST_OS=win_b64
set CommonProgramFiles=C:\Program Files (x86)\Common Files
set CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
set CommonProgramW6432=C:\Program Files\Common Files
set COMPUTERNAME=DESKTOP-KSO9BMI
set ComSpec=C:\Windows\system32\cmd.exe
set CorbaCppBuildROOT_PATH=\\ds\dsy\iona\Orbix3.3\win_b64
set CorbaCppROOT_PATH=\\ds\dsy\iona\Orbix3.3\win_b64
set CorbaJavaROOT_PATH=\\ds\dsy\iona\Orbix3.3\win_b64
set CSCSkipTestOfMapFileValidity=1
set DriverData=C:\Windows\System32\Drivers\DriverData
set DSXDEVVISUALCOMPILERVERSION=1.0-1.4
set FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
set FPS_BROWSER_USER_PROFILE_STRING=Default
set getRADE=C:\Users\ShiYi\AppData\Local\Temp\getRADE22229.bat
set HOMEDRIVE=C:
set HOMEPATH=\Users\ShiYi
set INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\atlmfc\include;C:\Program Files\Microsoft SDKs\Windows\v6.0A\include;D:\R21\Rade21\intel_a\.\tools\include\win_b64;D:\R21\Rade21\intel_a\.\tools\include
set JLMDeployROOT_PATH=D:\R21\Rade21\intel_a\.\jlm\jlmdeploy65
set LIB=C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\lib\amd64;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\atlmfc\lib\amd64;C:\Program Files\Microsoft SDKs\Windows\v6.0A\lib\x64;C:\Windows\Microsoft.NET\Framework64\v3.5;C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.5;C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0;C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set LOCALAPPDATA=C:\Users\ShiYi\AppData\Local
set LOGONSERVER=\\DESKTOP-KSO9BMI
set mkcsbuild=502111104
set mkcsClientMode=1
set mkcsINSTALL_PATH=D:\R21\Rade21
set mkcsOS_Buildtime=win_b64
set mkcsOS_NAME=Windows_NT
set mkcsOS_Runtime=intel_a
set mkcsROOT_PATH=D:\R21\Rade21\intel_a
set mkcsSHLIB_NAME=PATH
set mkcsSHLIB_PATH=D:\R21\Rade21\intel_a\code\bin
set mkcsVERSION=5.21.0.11104 (built Thu, Apr 14, 2011 at 20:00)
set MkmkADDON_INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\atlmfc\include;C:\Program Files\Microsoft SDKs\Windows\v6.0A\include;D:\R21\Rade21\intel_a\.\tools\include\win_b64;D:\R21\Rade21\intel_a\.\tools\include
set MkmkADDON_LEVEL=MK_CATIAVER=5 MK_BITMODE=64 MK_MSCVER=1500 MK_IFVER=1001011 MK_ORBIXCPP33 MK_ORBIXJAVA33
set MkmkADDON_LIB=C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\lib\amd64;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\atlmfc\lib\amd64;C:\Program Files\Microsoft SDKs\Windows\v6.0A\lib\x64;C:\Windows\Microsoft.NET\Framework64\v3.5;C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.5;C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0;C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set MkmkADDON_PATH=C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\amd64;C:\Program Files\Microsoft SDKs\Windows\v6.0A\bin\x64;C:\Windows\Microsoft.NET\Framework64\v3.5;C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.5;C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0;C:\Windows\Microsoft.NET\Framework64\v2.0.50727;C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE;D:\R21\Rade21\intel_a\code\command
set MkmkBAD_MINITFLEVEL=4
set mkmkbuild=502111104
set MkmkDELPHI50Internal=yes
set MkmkDictionary_PATH=D:\R21\Rade21\intel_a\code\dictionary
set MkmkExternalDS=External
set MkmkIC_PATH=D:\R21\Rade21\intel_a\code\productIC
set MkmkIF101Internal=101.011
set MkmkINSTALL_PATH=D:\R21\Rade21
set MkmkJDK16Internal=0_14
set MkmkMsgCatalog_PATH=D:\R21\Rade21\intel_a\resources\msgcatalog
set MkmkMSNET30DIR=C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0
set MkmkMSNET35DIR=C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.5
set MkmkMSPSDKDIR=C:\Program Files\Microsoft SDKs\Windows\v6.0A
set MkmkMSVCDIR=C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC
set MkmkMSVCSHARPDIR=C:\Windows\Microsoft.NET\Framework64\v3.5
set MkmkMSVJSHARPDIR=C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set MkmkMSVSBINDIR=C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE
set MkmkMSVSTOOLSBINDIR=C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\Tools\Bin
set MkmkOS_BitMode=64
set MkmkOS_Buildtime=win_b64
set MkmkOS_DOC=DOC
set MkmkOS_NAME=Windows_NT
set MkmkOS_Runtime=intel_a
set MkmkOS_Type=Windows
set MkmkOS_VAR=win_b64
set MkmkPATH4TOOLS=C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\amd64;C:\Program Files\Microsoft SDKs\Windows\v6.0A\bin\x64;C:\Windows\Microsoft.NET\Framework64\v3.5;C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.5;C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0;C:\Windows\Microsoft.NET\Framework64\v2.0.50727;C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn;C:\Users\ShiYi\AppData\Local\Microsoft\WindowsApps;D:\R21\Rade21\intel_a\TCK\command
set MkmkReffiles_PATH=D:\R21\Rade21\intel_a\reffiles
set MkmkRMSSDK_PATH=D:\R21\Rade21\intel_a\.\rms\rmssdksp2
set MkmkROOTINSTALL_PATH=D:\R21\Rade21\intel_a
set MkmkROOT_PATH=D:\R21\Rade21\intel_a
set MkmkSHLIB_NAME=PATH
set MkmkSHLIB_PATH=D:\R21\Rade21\intel_a\code\bin
set MkmkTOOLSINCLUDE_PATH=D:\R21\Rade21\intel_a\.\tools\include\win_b64;D:\R21\Rade21\intel_a\.\tools\include
set MkmkTOOLSLIB_PATH=D:\R21\Rade21\intel_a\.\tools\lib
set MkmkVERSION=5.21.0.11104 (built Thu, Apr 14, 2011 at 20:00)
set MkmkVERSIONINFO=NO
set MkmkVS90Internal=yes
set MkmkXMLMANIFEST=NO
set Mkmk_Modifier=1578
set Mkmk_Modifier_BAD=16
set MKMK_USEPRECOMPIL=yes
set MkodtOS_Runtime=win_b64
set MK_DEVNULL=NUL
set MK_SEPARATOR=;
set MK_TEMPDIR=C:\Users\ShiYi\AppData\Local\Temp
set NO_LOCAL_DEFINITION_FOR_IID=yes
set NUMBER_OF_PROCESSORS=8
set OneDrive=C:\Users\ShiYi\OneDrive
set OneDriveConsumer=C:\Users\ShiYi\OneDrive
set OS=Windows_NT
set PATH=C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\amd64;C:\Program Files\Microsoft SDKs\Windows\v6.0A\bin\x64;C:\Windows\Microsoft.NET\Framework64\v3.5;C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.5;C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0;C:\Windows\Microsoft.NET\Framework64\v2.0.50727;C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn;C:\Users\ShiYi\AppData\Local\Microsoft\WindowsApps;D:\R21\Rade21\intel_a\TCK\command;D:\R21\Rade21\intel_a\code\command;D:\R21\Rade21\intel_a\code\command
set PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
set PROCESSOR_ARCHITECTURE=AMD64
set PROCESSOR_ARCHITEW6432=AMD64
set PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
set PROCESSOR_LEVEL=6
set PROCESSOR_REVISION=8e0c
set ProgramData=C:\ProgramData
set ProgramFiles=C:\Program Files (x86)
set ProgramFiles(x86)=C:\Program Files (x86)
set ProgramW6432=C:\Program Files
set PROMPT=$P$G
set PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
set PUBLIC=C:\Users\Public
set RADECATSettingPath=C:\Users\ShiYi\AppData\Roaming\DassaultSystemes\CATSettings\RADE
set RELEASEMANAGER_PATH=D:\R21\Rade21\intel_a
set rtcode=0
set SESSIONNAME=Console
set SystemDrive=C:
set SystemRoot=C:\Windows
set TCKHelp=-
set TCKOS_Runtime=intel_a
set TCK_DATE=2019/11/20-10:56:11
set TCK_ID=V5R21_B21
set TCK_INSTALL_PATH=D:\R21\Rade21
set TCK_LOCAL_INFO=C:\Program Files (x86)
set TCK_NAME=V5R21_B21
set TCK_NO_SERVER=true
set TCK_ROOT_PATH=D:\R21\Rade21\intel_a
set TCK_TMP_FILE=C:\Users\ShiYi\AppData\Local\Temp\tckexec__ShiYi_20941.bat
set TEMP=C:\Users\ShiYi\AppData\Local\Temp
set TMP=C:\Users\ShiYi\AppData\Local\Temp
set USERDOMAIN=DESKTOP-KSO9BMI
set USERDOMAIN_ROAMINGPROFILE=DESKTOP-KSO9BMI
set USERNAME=ShiYi
set USERPROFILE=C:\Users\ShiYi
set VBTtmp=C:\Users\ShiYi\AppData\Local\Temp
set VisualStudioDir=C:\Users\ShiYi\Documents\Visual Studio 2008
set VS90COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\Tools\
set WecVersionForRosebud.18D8=2
set windir=C:\Windows
set _tck_exec=OK
set __COMPAT_LAYER=ElevateCreateProcess
