# COPYRIGHT Dassault Systemes 2020
#======================================================================
# Imakefile for module SYTestMod.m
#======================================================================
#
#  May 2020  Creation: Code generated by the CAA wizard  ShiYi
#======================================================================
#
# LOAD MODULE 
#
BUILT_OBJECT_TYPE=LOAD MODULE 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP \
SYExcelRefMod \
SYGlobalFunctionMod \
CATXMLParserItf 
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES)

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
