# COPYRIGHT Dassault Systemes 2009
#======================================================================
# Imakefile for module JDAPointItf.m 
#======================================================================
#
#  Apr 2009  Creation: Code generated by the CAA wizard  LuJun
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = \
    JS0GROUP   \
JS0FM JDAPointInterfacesUUID KnowledgeItf
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES) 

INCLUDED_MODULES = \
                  JDAPointItfCPP \
