E:\01_DevWorkSpace\01_WinWS_CAA\WSWinhoPubLib\.\WinhoDebugTool\various\win_b64\HList\PrivateInterfaces.hl
E:\01_DevWorkSpace\01_WinWS_CAA\WSWinhoPubLib\.\WinhoDebugTool\various\win_b64\HList\ProtectedInterfaces.hl
E:\01_DevWorkSpace\01_WinWS_CAA\WSWinhoPubLib\.\WinhoDebugTool\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ApplicationFrame\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ApplicationFrame\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\BSFBuildtimeData\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\BSFBuildtimeData\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\DialogEngine\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\DialogEngine\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\GeometricObjects\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\GeometricObjects\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\KnowledgeInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\KnowledgeInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\Mathematics\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\Mathematics\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\MeasureGeometryInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\MeasureGeometryInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\MecModInterfaces\various\win_b64\HList\PrivateInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\MecModInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\MecModInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\NewTopologicalObjects\various\win_b64\HList\PrivateInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\NewTopologicalObjects\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\NewTopologicalObjects\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ObjectModelerBase\various\win_b64\HList\PrivateInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ObjectModelerBase\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ObjectModelerBase\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ObjectSpecsModeler\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ObjectSpecsModeler\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ProductStructure\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ProductStructure\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\System\various\win_b64\HList\PrivateInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\System\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\System\various\win_b64\HList\PublicInterfaces.hl
E:\01_DevWorkSpace\01_WinWS_CAA\WSWinhoPubLib\.\WinhoCAAPubLib\various\win_b64\HList\PublicInterfaces.hl
E:\01_DevWorkSpace\01_WinWS_CAA\WSWinhoPubLib\.\WinhoDBPubLib\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\Administration\various\win_b64\HList\PrivateInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\Administration\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\Administration\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\AdvancedMathematics\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\AdvancedMathematics\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\AdvancedTopologicalOpe\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\AdvancedTopologicalOpe\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\AdvancedTopologicalOpeLight\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\AdvancedTopologicalOpeLight\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\AutomationInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\AutomationInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\BasicTopologicalOpe\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\BasicTopologicalOpe\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\BatchInfrastructure\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\BatchInfrastructure\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CAT3DXmlInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CAT3DXmlInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATAssemblyInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATAssemblyInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATCDS\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATCDS\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATCDSUtilities\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATCDSUtilities\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATCGMSkmDataItf\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATCGMSkmDataItf\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATCloudBasicResources\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATCloudBasicResources\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATDataCompatibilityInfra\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATDataCompatibilityInfra\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATElfiniOpenSoftware\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATElfiniOpenSoftware\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATFuzzyOperators\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATFuzzyOperators\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATGraphicProperties\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATGraphicProperties\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATIAApplicationFrame\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATIAApplicationFrame\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATIADataBasics\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATIADataBasics\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATIADataMacFortran\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATIADataMacFortran\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATImmWtpInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATImmWtpInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATJavaBridge\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATJavaBridge\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATMecModExtendItf\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATMecModExtendItf\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATMecModLiveUseItf\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATMecModLiveUseItf\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATMecModUseItf\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATMecModUseItf\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATPDMBaseInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATPDMBaseInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATPLMDictionary\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATPLMDictionary\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATShfInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATShfInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATShmInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATShmInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATSmarTeamIntegInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATSmarTeamIntegInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATSubdivisionApproximation\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATSubdivisionApproximation\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATSubdivisionMeshOperators\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATSubdivisionMeshOperators\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATSubdivisionObjects\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATSubdivisionObjects\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATTPSInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATTPSInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATTTRSInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATTTRSInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATTechResultInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATTechResultInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATTechnologicalPackageUIItf\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATTechnologicalPackageUIItf\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATV4DataAdmin\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATV4DataAdmin\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATV4System\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATV4System\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATVirtualVaultSystem\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATVirtualVaultSystem\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATWBx\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATWBx\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATXDocLinkInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CATXDocLinkInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CDMOperatorsInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CDMOperatorsInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CGMV5Interoperability\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CGMV5Interoperability\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CGMV5SpecsQuery\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CGMV5SpecsQuery\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CORBARuntime\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CORBARuntime\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\Communications\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\Communications\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ComponentsCatalogsInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ComponentsCatalogsInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ConstraintModeler\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ConstraintModeler\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ConstraintModelerInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ConstraintModelerInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ConstraintSolver\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ConstraintSolver\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CurveBasedGeoOperators\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CurveBasedGeoOperators\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CurveBasedInfrastructure\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CurveBasedInfrastructure\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CurveBasedMathematics\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CurveBasedMathematics\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CurveBasedTopoOperators\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\CurveBasedTopoOperators\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\DCM2D\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\DCM2D\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\DCM3D\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\DCM3D\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\DMAPSInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\Dialog\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\Dialog\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\DraftingInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\DraftingInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ENOVaultClientCPP\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\FeatureCommands\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\FeatureCommands\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\FileMenu\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\FileMenu\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\FreeFormOperators\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\FreeFormOperators\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\FreeStyleAnalysisInterface\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\FreeStyleAnalysisInterface\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\GMAdvancedOperatorsInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\GMAdvancedOperatorsInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\GMModelInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\GMModelInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\GMOperatorsInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\GMOperatorsInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\GSMInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\GSMInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\GenericNaming\various\win_b64\HList\PrivateInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\GenericNaming\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\GenericNaming\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\GeometricObjectsCGM\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\GeometricObjectsCGM\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\GeometricOperators\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\GeometricOperators\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\GeometryVisualization\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\GeometryVisualization\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\Graph\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\Graph\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\HLRBase\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\HLRBase\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\InfInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\InfInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\Infra2DInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\Infra2DInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\InteractiveInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\InteractiveInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\KnowledgeModeler\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\KnowledgeModeler\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\LCCommon\various\win_b64\HList\PrivateInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\LCCommon\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\LCCommon\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\LiteralFeatures\various\win_b64\HList\PrivateInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\LiteralFeatures\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\LiteralFeatures\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\LiteralsEditor\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\LiteralsEditor\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\Mainwin\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\Mainwin\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\MechanicalCommands\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\MechanicalCommands\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\MechanicalModeler\various\win_b64\HList\PrivateInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\MechanicalModeler\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\MechanicalModeler\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\MechanicalModelerUI\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\Multimedia\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\Multimedia\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ObjectModelerBaseUI\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ObjectModelerBaseUI\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ObjectModelerCATIA\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ObjectModelerCATIA\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ObjectModelerCATSDM\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ObjectModelerCATSDM\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ObjectModelerCollection\various\win_b64\HList\PrivateInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ObjectModelerCollection\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ObjectModelerCollection\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ObjectModelerInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ObjectModelerInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ObjectModelerNavigator\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ObjectModelerNavigator\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ObjectModelerSDM\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ObjectModelerSDM\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ObjectModelerSystem\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ObjectModelerSystem\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\PartInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\PartInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\PolygonalTools\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\PolygonalTools\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\PolyhedralInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\PolyhedralInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\PolyhedralMathematics\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\PolyhedralMathematics\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\PolyhedralObjects\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\PolyhedralObjects\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\PolyhedralOperators\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\PolyhedralOperators\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\PolyhedralVisuOperators\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\PolyhedralVisuOperators\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\PolyhedralVisualization\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\PolyhedralVisualization\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\Print\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\Print\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\PrintBase\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\PrintBase\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ProductStructureInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\ProductStructureInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\SDMBinaryForm\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\SDMBinaryForm\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\SDMRuntime\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\SDMRuntime\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\SDMSTEPForm\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\SDMSTEPForm\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\SGMOperatorsInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\SGMOperatorsInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\SketcherInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\SketcherInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\SketcherModeler\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\SketcherModeler\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\SketcherToolsUI\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\SketcherToolsUI\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\SpecialAPI\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\SpecialAPI\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\SurfacicGeoOperators\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\SurfacicGeoOperators\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\SurfacicInfrastructure\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\SurfacicInfrastructure\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\SurfacicMathematics\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\SurfacicMathematics\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\SurfacicTopoOperators\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\SurfacicTopoOperators\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\Tessellation\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\Tessellation\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\TopologicalOperators\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\TopologicalOperators\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\TopologicalOperatorsLight\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\TopologicalOperatorsLight\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\VBA\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\VBA\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\Visualization\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\Visualization\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\VisualizationBase\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\VisualizationBase\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\XMLParser\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\XMLParser\various\win_b64\HList\PublicInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\XlatorCGM\various\win_b64\HList\ProtectedInterfaces.hl
C:\WinhoMBE\DassaultSystemes\V5R21\B21\.\XlatorCGM\various\win_b64\HList\PublicInterfaces.hl
