// COPYRIGHT Dassault Systemes 2009
//===================================================================
//
// JDAEPTMemoVisProperties.cpp
// Provide implementation to interface
//    CATIVisProperties
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Apr 2009  Creation: Code generated by the CAA wizard  LuJun
//===================================================================
#include "JDAEPTMemoVisProperties.h"
#include "iostream.h"

 
CATImplementClass(JDAEPTMemoVisProperties,
                  DataExtension,
                  CATExtIVisProperties,
                  JDAPTMemo );
 

//-----------------------------------------------------------------------------
// JDAEPTMemoVisProperties : constructor
//-----------------------------------------------------------------------------
JDAEPTMemoVisProperties::JDAEPTMemoVisProperties():
    CATExtIVisProperties()
{
}

//-----------------------------------------------------------------------------
// JDAEPTMemoVisProperties : destructor
//-----------------------------------------------------------------------------
JDAEPTMemoVisProperties::~JDAEPTMemoVisProperties()
{
}
 
// Link the implementation to its interface
// ---------------------------------------



//TIE or TIEchain definitions
#include "TIE_CATIVisProperties.h"
TIE_CATIVisProperties( JDAEPTMemoVisProperties);

HRESULT JDAEPTMemoVisProperties::IsGeomTypeDefined(CATVisGeomType& iGeomType)
{
	//cout <<"==> Now we are in JDAEPTMemoVisProperties::IsGeomTypeDefined  !" << endl;

	HRESULT result = E_FAIL;
	switch (iGeomType)	
	{
		case CATVPGlobalType:
			result = S_OK;
			break; 
		case CATVPPoint:
			result = S_OK;
			break;
	}

	//cout <<"==> Now end JDAEPTMemoVisProperties::IsGeomTypeDefined  !" << endl;

	return result;
}


HRESULT JDAEPTMemoVisProperties::GetSubTypeFromPath(
                                     CATPathElement     & iPathElement,
                                     CATVisPropertyType   iPropertyType,
                                     CATVisGeomType     & oGeomType,
                                     unsigned int       & oPropertyNumber )
{
	//cout <<"==> Now we are in JDAEPTMemoVisProperties::GetSubTypeFromPath  !" << endl;

	oGeomType = CATVPPoint;
	oPropertyNumber = 0;

	//cout <<"==> Now end JDAEPTMemoVisProperties::GetSubTypeFromPath  !" << endl;

	return S_OK;
}



//Methods implementation

