// COPYRIGHT Dassault Systemes 2009
//===================================================================
//
// JDAEPTMemoNodeNavig.cpp
// Provide implementation to interface
//    CATINavigModify
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Apr 2009  Creation: Code generated by the CAA wizard  LuJun
//===================================================================
#include "JDAEPTMemoNodeNavig.h"
#include "CATUnicodeString.h"
#include "CATIGraphNode.h"

#include "iostream.h"


 
CATImplementClass(JDAEPTMemoNodeNavig,
                  DataExtension,
                  CATNodeExtension,
                  JDAPTMemo_node );
 

//-----------------------------------------------------------------------------
// JDAEPTMemoNodeNavig : constructor
//-----------------------------------------------------------------------------
JDAEPTMemoNodeNavig::JDAEPTMemoNodeNavig():
    CATNodeExtension()
{
}

//-----------------------------------------------------------------------------
// JDAEPTMemoNodeNavig : destructor
//-----------------------------------------------------------------------------
JDAEPTMemoNodeNavig::~JDAEPTMemoNodeNavig()
{
}
 
// Link the implementation to its interface
// ---------------------------------------



//TIE or TIEchain definitions
#include "TIE_CATINavigModify.h"
TIE_CATINavigModify( JDAEPTMemoNodeNavig);


//Methods implementation

//-----------------------------------------------------------------------------
// Implements CATINavigModify::UpdateElem
//-----------------------------------------------------------------------------
void JDAEPTMemoNodeNavig::UpdateElem (CATNavigInstance*  iInst)
{

	//cout <<"==> Now we are in JDAEPTMemoNodeNavig::UpdateElem  !" << endl;

	CATIGraphNode_var spNode = this;

	CATUnicodeString sIcon ("I_Note");
	spNode->SetPixelImage(sIcon);
	spNode->SetDecoration(0);

	//cout <<"==> Now end JDAEPTMemoNodeNavig::UpdateElem  !" << endl;

	return;

}

//-----------------------------------------------------------------------------
// Implements CATINavigModify::ModifyShortHelp
//-----------------------------------------------------------------------------
//HRESULT JDAEPTMemoNodeNavig::ModifyShortHelp (CATUnicodeString&  ioText)
//{
//	cout <<"==> Now we are in JDAEPTMemoNodeNavig::ModifyShortHelp  !" << endl;
//
//   return S_OK;
//}
//
//-----------------------------------------------------------------------------
// Implements CATINavigModify::Select
//-----------------------------------------------------------------------------
//void JDAEPTMemoNodeNavig::Select (int  iMode)
//{
//
//	cout <<"==> Now we are in JDAEPTMemoNodeNavig::Select  !" << endl;
//   return;
//}
//
//-----------------------------------------------------------------------------
// Implements CATINavigModify::IsSelected
//-----------------------------------------------------------------------------
//int JDAEPTMemoNodeNavig::IsSelected ()
//{
//
//	cout <<"==> Now we are in JDAEPTMemoNodeNavig::IsSelected  !" << endl;
//
//   return 0;
//}

