// COPYRIGHT Dassault Systemes 2015
//===================================================================
//
// SJDPartExampleDlg.cpp
// The dialog : SJDPartExampleDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Jan 2015  Creation: Code generated by the CAA wizard  LuJunHome
//===================================================================
#include "SJDPartExampleDlg.h"
#include "CATApplicationFrame.h"
#include "CATDlgGridConstraints.h"
#include "CATMsgCatalog.h"
#ifdef SJDPartExampleDlg_ParameterEditorInclude
#include "CATIParameterEditorFactory.h"
#include "CATIParameterEditor.h"
#include "CATICkeParm.h"
#endif




//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
SJDPartExampleDlg::SJDPartExampleDlg() :
  CATDlgDialog ((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(),
//CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
"SJDPartExampleDlg",CATDlgWndBtnOKApplyClose|CATDlgGridLayout
//END CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
                               )
{
//CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
 _FrameViewer = NULL;
 _FrameFile = NULL;
 _LabelFile = NULL;
 _ComboFile = NULL;
//END CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
SJDPartExampleDlg::~SJDPartExampleDlg()
{
//  Do not delete the control elements of your dialog: 
//     this is done automatically
//  --------------------------------------------------
//CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
 _FrameViewer = NULL;
 _FrameFile = NULL;
 _LabelFile = NULL;
 _ComboFile = NULL;
//END CAA2 WIZARD DESTRUCTOR DECLARATION SECTION

 _pViewer3D = NULL;
}



void SJDPartExampleDlg::Build()
{
//  TODO: This call builds your dialog from the layout declaration file
//  -------------------------------------------------------------------

//CAA2 WIZARD WIDGET CONSTRUCTION SECTION
 _FrameViewer = new CATDlgFrame(this, "FrameViewer", CATDlgFraNoTitle|CATDlgGridLayout);
_FrameViewer -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _FrameFile = new CATDlgFrame(this, "FrameFile", CATDlgGridLayout);
_FrameFile -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _LabelFile = new CATDlgLabel(_FrameFile, "LabelFile");
_LabelFile -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _ComboFile = new CATDlgCombo(_FrameFile, "ComboFile", CATDlgCmbDropDown);
_ComboFile -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
//END CAA2 WIZARD WIDGET CONSTRUCTION SECTION

_pViewer3D = new CATNavigation3DViewer(_FrameViewer,"DlgVeiwer3D",CATDlgFraNoTitle|CATDlgFraNoFrame,200,140);
_pViewer3D -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
_FrameViewer->Attach4Sides(_pViewer3D);

//Init the value
_ComboFile->SetLine(CATUnicodeString("No Selection"));
_ComboFile->SetLine(CATUnicodeString("Part1"));
_ComboFile->SetLine(CATUnicodeString("Part2"));
_ComboFile->SetLine(CATUnicodeString("Part3"));
_ComboFile->SetLine(CATUnicodeString("Part4"));
}

CATNavigation3DViewer * SJDPartExampleDlg::GetViewer3D()
{
	return _pViewer3D;
}

CATDlgCombo * SJDPartExampleDlg::GetCombo()
{
	return _ComboFile;
}