// COPYRIGHT Dassault Systemes 2009
//===================================================================
//
// JDAEPTBaseNavigate.h
// Provide implementation to interface
//    CATINavigateObject

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	JDAPTBase
//EXTENSIONTYPE:	DataExtension

//    TIE: CATINavigateObject

//End CAA2 Wizard Generation Report
//
//  Apr 2009  Creation: Code generated by the CAA wizard  LuJun
//===================================================================
#ifndef JDAEPTBaseNavigate_H
#define JDAEPTBaseNavigate_H

#include "CATBaseUnknown.h"
class CATListValCATUnicodeString;
class CATListValCATBaseUnknown_var;

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href CATINavigateObject
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class JDAEPTBaseNavigate: public CATBaseUnknown

{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     JDAEPTBaseNavigate ();
     virtual ~JDAEPTBaseNavigate ();

    /**
     * Implements a function from an interface.
     * @href CATINavigateObject#GetIdentificators
     */
     CATListValCATUnicodeString* GetIdentificators () ;

    /**
     * Implements a function from an interface.
     * @href CATINavigateObject#GetChildren
     */
     CATListValCATBaseUnknown_var* GetChildren () ;


  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  JDAEPTBaseNavigate (JDAEPTBaseNavigate &);
  JDAEPTBaseNavigate& operator=(JDAEPTBaseNavigate&);

};

//-----------------------------------------------------------------------

#endif
