// COPYRIGHT Dassault Systemes 2009
//===================================================================
//
// JDAEPTRoot3DVisu.h
// Provide implementation to interface
//    CATI3DGeoVisu

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	JDAPTRoot
//EXTENSIONTYPE:	DataExtension

//    TIE: CATI3DGeoVisu

//End CAA2 Wizard Generation Report
//
//  Apr 2009  Creation: Code generated by the CAA wizard  LuJun
//===================================================================
#ifndef JDAEPTRoot3DVisu_H
#define JDAEPTRoot3DVisu_H

#include "CATExtIVisu.h"
#include "CATRep.h"

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href CATI3DGeoVisu
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class JDAEPTRoot3DVisu: public CATExtIVisu

{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     JDAEPTRoot3DVisu ();
     virtual ~JDAEPTRoot3DVisu ();
	CATRep * BuildRep ();

  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  JDAEPTRoot3DVisu (JDAEPTRoot3DVisu &);
  JDAEPTRoot3DVisu& operator=(JDAEPTRoot3DVisu&);

};

//-----------------------------------------------------------------------

#endif
