// COPYRIGHT Dassault Systemes 2009
//===================================================================
//
// JDAEPTProductAddin.h
// Provide implementation to interface
//    CATIPrsConfigurationAddin

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	JDAPTProductAddin
//EXTENSIONTYPE:	DataExtension

//    TIE: CATIPrsConfigurationAddin

//End CAA2 Wizard Generation Report
//
//  Apr 2009  Creation: Code generated by the CAA wizard  LuJun
//===================================================================
#ifndef JDAEPTProductAddin_H
#define JDAEPTProductAddin_H

#include "CATBaseUnknown.h"
class CATCmdContainer;

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href CATIPrsConfigurationAddin
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class JDAEPTProductAddin: public CATBaseUnknown

{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     JDAEPTProductAddin ();
     virtual ~JDAEPTProductAddin ();

	 void CreateCommands();
     CATCmdContainer *CreateToolbars();

  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  JDAEPTProductAddin (JDAEPTProductAddin &);
  JDAEPTProductAddin& operator=(JDAEPTProductAddin&);

};

//-----------------------------------------------------------------------

#endif
