// COPYRIGHT Dassault Systemes 2009
//===================================================================
//
// JDAPTProductCreateEditMemoCmd.h
// The state chart based command: JDAPTProductCreateEditMemoCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   STATECOMMAND
//End CAA2 Wizard Generation Report
//
//  Apr 2009  Creation: Code generated by the CAA wizard  LuJun
//===================================================================
#ifndef JDAPTProductCreateEditMemoCmd_H
#define JDAPTProductCreateEditMemoCmd_H

#include "CATStateCommand.h"
#include "CATBoolean.h"
#include "JDAPTCreateEditMemoDlg.h"
#include "CATIProduct.h"
#include  "JDAIPTMemo.h"

//class CATIndicationAgent;

//----------------------------------------------------------------------

/**
 * Describe your command here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog engine framework.
 * (consult base class description).
 */
class JDAPTProductCreateEditMemoCmd: public CATStateCommand
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( JDAPTProductCreateEditMemoCmd, CATStateCommand )

  public:

  JDAPTProductCreateEditMemoCmd(JDAIPTMemo *ipiMemo);
  virtual ~JDAPTProductCreateEditMemoCmd();

    /**
     * Defines the command automata.
     * <br>
     * <i>(states, transitions and agents)</i>
     */
  virtual void     BuildGraph();
  virtual CATBoolean  OkAction(void * data);
  virtual CATBoolean  CloseAction(void * data);
  virtual CATBoolean  ApplyAction(void * data);
  //virtual CATBoolean  PointSelectedAction(void * data);


    /**
     * Action associated to state transitions.
     */
  //virtual CATBoolean  ActionOne(void * data);

  private:

  //CATIndicationAgent	* _Indication;
    CATDialogAgent * _OkAgent;
    CATDialogAgent * _CloseAgent;
	CATDialogAgent * _ApplyAgent;
    //CATPathElementAgent *_Indication;
    //CATIProduct *_piProduct;
    //CATPoint *_piPoint;
    JDAPTCreateEditMemoDlg *_Panel;
    JDAIPTMemo *_piMemo;

};

//----------------------------------------------------------------------

#endif
