// COPYRIGHT Dassault Systemes 2009
//===================================================================
//
// JDAEPTProductAddin.cpp
// Provide implementation to interface
//    CATIPrsConfigurationAddin
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Apr 2009  Creation: Code generated by the CAA wizard  LuJun
//===================================================================
#include "JDAEPTProductAddin.h"
#include "CATCommandHeader.h"
#include "CATCreateWorkshop.h"

//---------- Code generated by Jiangda CAAPlugin wizard

// ProductStructureUI
#include "CATIPrsConfigurationAddin.h"

// ApplicationFrame
#include "CATCmdContainer.h"

//---------- End Code generated by Jiangda CAAPlugin wizard


MacDeclareHeader(JDAPTProductHeader)

 
CATImplementClass(JDAEPTProductAddin,
                  DataExtension,
                  CATBaseUnknown,
                  JDAPTProductAddin );
 

//-----------------------------------------------------------------------------
// JDAEPTProductAddin : constructor
//-----------------------------------------------------------------------------
JDAEPTProductAddin::JDAEPTProductAddin():
    CATBaseUnknown()
{
}

//-----------------------------------------------------------------------------
// JDAEPTProductAddin : destructor
//-----------------------------------------------------------------------------
JDAEPTProductAddin::~JDAEPTProductAddin()
{
}
 
// Link the implementation to its interface
// ---------------------------------------

//TIE or TIEchain definitions
#include "TIE_CATIPRDWorkshopAddin.h"
TIE_CATIPRDWorkshopAddin( JDAEPTProductAddin);

void JDAEPTProductAddin::CreateCommands()
{

  new JDAPTProductHeader("Create",
                      "JDAPTCommands",
                      "JDAPTProductCreateEditMemoCmd",
                      (void *) NULL);
  new JDAPTProductHeader("Show",
	  "JDAPTCommands",
	  "JDAPTProductShowCmd",
	  (void *) NULL);

  //new TSTAnoProductHeader("AnoUpdate",
  //                    "TSTAnoCommands",
  //                    "TSTAnoUpdateCmd",
  //                    (void *) NULL);
}

CATCmdContainer *JDAEPTProductAddin::CreateToolbars()
{
  NewAccess(CATCmdContainer, pMyToolbar, AnoToolBar);

  NewAccess(CATCmdStarter, pMyButton1, Button1);
  SetAccessCommand(pMyButton1, "Create");
  SetAccessChild(pMyToolbar, pMyButton1);

  NewAccess(CATCmdStarter, pMyButton2, Button2);
  SetAccessCommand(pMyButton2, "Show");
  SetAccessNext(pMyButton1, pMyButton2);

  AddToolbarView(pMyToolbar, 1, Right);

  return pMyToolbar;
}


//Methods implementation

