// COPYRIGHT 上海文颢信息技术有限公司 2018
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework WinhoDebugTool
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Apr 2018  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("System",Protected);
AddPrereqComponent("ApplicationFrame",Protected);
// END WIZARD EDITION ZONE
AddPrereqComponent("ObjectModelerBase",Protected);
AddPrereqComponent("ObjectSpecsModeler",Protected);
AddPrereqComponent("WinhoCAAPubLib",Public);
AddPrereqComponent("WinhoDBPubLib",Public);
AddPrereqComponent("ProductStructure",Public); 
AddPrereqComponent("Mathematics",Public); 
AddPrereqComponent("MecModInterfaces",Protected);
AddPrereqComponent("KnowledgeInterfaces",Protected);
AddPrereqComponent("GeometricObjects",Protected);
AddPrereqComponent("NewTopologicalObjects",Protected);
AddPrereqComponent("MeasureGeometryInterfaces",Protected);
AddPrereqComponent("DialogEngine",Protected); 
