E:\Program\CAA\CATIA\tmpTest\SJDDisplayDocInMyViewerWsp\.\SJDPartExampleFrm\various\intel_a\HList\PrivateInterfaces.hl
E:\Program\CAA\CATIA\tmpTest\SJDDisplayDocInMyViewerWsp\.\SJDPartExampleFrm\various\intel_a\HList\ProtectedInterfaces.hl
E:\Program\CAA\CATIA\tmpTest\SJDDisplayDocInMyViewerWsp\.\SJDPartExampleFrm\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\ApplicationFrame\various\intel_a\HList\ProtectedInterfaces.hl
D:\DS\B19_32\.\ApplicationFrame\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\AutomationInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
D:\DS\B19_32\.\AutomationInterfaces\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\BatchInfrastructure\various\intel_a\HList\ProtectedInterfaces.hl
D:\DS\B19_32\.\BatchInfrastructure\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\CATDataCompatibilityInfra\various\intel_a\HList\ProtectedInterfaces.hl
D:\DS\B19_32\.\CATDataCompatibilityInfra\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\CATIADataBasics\various\intel_a\HList\ProtectedInterfaces.hl
D:\DS\B19_32\.\CATIADataBasics\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\CATJavaBridge\various\intel_a\HList\ProtectedInterfaces.hl
D:\DS\B19_32\.\CATJavaBridge\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\CATPDMBaseInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
D:\DS\B19_32\.\CATPDMBaseInterfaces\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\CATPLMDictionary\various\intel_a\HList\ProtectedInterfaces.hl
D:\DS\B19_32\.\CATPLMDictionary\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\CATTechnologicalPackageUIItf\various\intel_a\HList\ProtectedInterfaces.hl
D:\DS\B19_32\.\CATTechnologicalPackageUIItf\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\CATVirtualVaultSystem\various\intel_a\HList\ProtectedInterfaces.hl
D:\DS\B19_32\.\CATVirtualVaultSystem\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\Communications\various\intel_a\HList\ProtectedInterfaces.hl
D:\DS\B19_32\.\Communications\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\Dialog\various\intel_a\HList\ProtectedInterfaces.hl
D:\DS\B19_32\.\Dialog\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\DialogEngine\various\intel_a\HList\ProtectedInterfaces.hl
D:\DS\B19_32\.\DialogEngine\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\GSMInterfaces\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\Graph\various\intel_a\HList\ProtectedInterfaces.hl
D:\DS\B19_32\.\Graph\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\InfInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
D:\DS\B19_32\.\InfInterfaces\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\InteractiveInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
D:\DS\B19_32\.\InteractiveInterfaces\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\KnowledgeInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
D:\DS\B19_32\.\KnowledgeInterfaces\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\Mainwin\various\intel_a\HList\ProtectedInterfaces.hl
D:\DS\B19_32\.\Mainwin\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\Mathematics\various\intel_a\HList\ProtectedInterfaces.hl
D:\DS\B19_32\.\Mathematics\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\MecModInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
D:\DS\B19_32\.\MecModInterfaces\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\ObjectModelerBase\various\intel_a\HList\ProtectedInterfaces.hl
D:\DS\B19_32\.\ObjectModelerBase\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\ObjectModelerCATIA\various\intel_a\HList\ProtectedInterfaces.hl
D:\DS\B19_32\.\ObjectModelerCATIA\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\ObjectModelerCollection\various\intel_a\HList\PrivateInterfaces.hl
D:\DS\B19_32\.\ObjectModelerCollection\various\intel_a\HList\ProtectedInterfaces.hl
D:\DS\B19_32\.\ObjectModelerCollection\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\ObjectModelerInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
D:\DS\B19_32\.\ObjectModelerInterfaces\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\ObjectModelerNavigator\various\intel_a\HList\ProtectedInterfaces.hl
D:\DS\B19_32\.\ObjectModelerNavigator\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\ObjectModelerSystem\various\intel_a\HList\ProtectedInterfaces.hl
D:\DS\B19_32\.\ObjectModelerSystem\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\ObjectSpecsModeler\various\intel_a\HList\ProtectedInterfaces.hl
D:\DS\B19_32\.\ObjectSpecsModeler\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\ProductStructureInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
D:\DS\B19_32\.\ProductStructureInterfaces\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\SketcherInterfaces\various\intel_a\HList\ProtectedInterfaces.hl
D:\DS\B19_32\.\SketcherInterfaces\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\SpecialAPI\various\intel_a\HList\ProtectedInterfaces.hl
D:\DS\B19_32\.\SpecialAPI\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\System\various\intel_a\HList\ProtectedInterfaces.hl
D:\DS\B19_32\.\System\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\VBA\various\intel_a\HList\ProtectedInterfaces.hl
D:\DS\B19_32\.\VBA\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\Visualization\various\intel_a\HList\ProtectedInterfaces.hl
D:\DS\B19_32\.\Visualization\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\VisualizationBase\various\intel_a\HList\ProtectedInterfaces.hl
D:\DS\B19_32\.\VisualizationBase\various\intel_a\HList\PublicInterfaces.hl
D:\DS\B19_32\.\XMLParser\various\intel_a\HList\ProtectedInterfaces.hl
D:\DS\B19_32\.\XMLParser\various\intel_a\HList\PublicInterfaces.hl
